# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiXYZ_V1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(564, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_Logger = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_Logger.setGeometry(QtCore.QRect(10, 480, 481, 101))
        self.textEdit_Logger.setObjectName("textEdit_Logger")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 561, 481))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBoxConnect = QtWidgets.QGroupBox(self.tab)
        self.groupBoxConnect.setGeometry(QtCore.QRect(0, 10, 311, 101))
        self.groupBoxConnect.setObjectName("groupBoxConnect")
        self.comboBox_COM = QtWidgets.QComboBox(self.groupBoxConnect)
        self.comboBox_COM.setGeometry(QtCore.QRect(150, 10, 69, 22))
        self.comboBox_COM.setObjectName("comboBox_COM")
        self.pushButton_Refresh = QtWidgets.QPushButton(self.groupBoxConnect)
        self.pushButton_Refresh.setGeometry(QtCore.QRect(10, 70, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Actions-view-refresh-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Refresh.setIcon(icon)
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.comboBox_ConnSpeed = QtWidgets.QComboBox(self.groupBoxConnect)
        self.comboBox_ConnSpeed.setGeometry(QtCore.QRect(150, 40, 69, 22))
        self.comboBox_ConnSpeed.setCurrentText("")
        self.comboBox_ConnSpeed.setObjectName("comboBox_ConnSpeed")
        self.label_COM = QtWidgets.QLabel(self.groupBoxConnect)
        self.label_COM.setGeometry(QtCore.QRect(10, 20, 47, 13))
        self.label_COM.setObjectName("label_COM")
        self.label_ConnSpeed = QtWidgets.QLabel(self.groupBoxConnect)
        self.label_ConnSpeed.setGeometry(QtCore.QRect(10, 40, 111, 16))
        self.label_ConnSpeed.setObjectName("label_ConnSpeed")
        self.pushButton_Connect = QtWidgets.QPushButton(self.groupBoxConnect)
        self.pushButton_Connect.setGeometry(QtCore.QRect(210, 70, 91, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/connect-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Connect.setIcon(icon1)
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.label_ConnectedStatus = QtWidgets.QLabel(self.groupBoxConnect)
        self.label_ConnectedStatus.setEnabled(True)
        self.label_ConnectedStatus.setGeometry(QtCore.QRect(240, 10, 51, 51))
        self.label_ConnectedStatus.setText("")
        self.label_ConnectedStatus.setPixmap(QtGui.QPixmap("img/connect-icon.png"))
        self.label_ConnectedStatus.setScaledContents(True)
        self.label_ConnectedStatus.setObjectName("label_ConnectedStatus")
        self.groupBox_XYZ = QtWidgets.QGroupBox(self.tab)
        self.groupBox_XYZ.setEnabled(False)
        self.groupBox_XYZ.setGeometry(QtCore.QRect(0, 110, 551, 341))
        self.groupBox_XYZ.setObjectName("groupBox_XYZ")
        self.pushButton_YUp = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YUp.setGeometry(QtCore.QRect(60, 30, 51, 51))
        self.pushButton_YUp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/Actions-go-Up-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_YUp.setIcon(icon2)
        self.pushButton_YUp.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YUp.setObjectName("pushButton_YUp")
        self.pushButton_XLeft = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XLeft.setGeometry(QtCore.QRect(10, 80, 51, 51))
        self.pushButton_XLeft.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/Actions-go-Left-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XLeft.setIcon(icon3)
        self.pushButton_XLeft.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XLeft.setObjectName("pushButton_XLeft")
        self.pushButton_XRight = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XRight.setGeometry(QtCore.QRect(110, 80, 51, 51))
        self.pushButton_XRight.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XRight.setIcon(icon4)
        self.pushButton_XRight.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XRight.setObjectName("pushButton_XRight")
        self.pushButton_YDown = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YDown.setGeometry(QtCore.QRect(60, 130, 51, 51))
        self.pushButton_YDown.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/Actions-go-Down-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_YDown.setIcon(icon5)
        self.pushButton_YDown.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YDown.setObjectName("pushButton_YDown")
        self.pushButton_ZUp = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_ZUp.setGeometry(QtCore.QRect(170, 30, 51, 51))
        self.pushButton_ZUp.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_ZUp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZUp.setIcon(icon6)
        self.pushButton_ZUp.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_ZUp.setObjectName("pushButton_ZUp")
        self.pushButton_ZDown = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_ZDown.setGeometry(QtCore.QRect(170, 130, 51, 51))
        self.pushButton_ZDown.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_Zdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZDown.setIcon(icon7)
        self.pushButton_ZDown.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_ZDown.setObjectName("pushButton_ZDown")
        self.lineEdit_X = QtWidgets.QLineEdit(self.groupBox_XYZ)
        self.lineEdit_X.setGeometry(QtCore.QRect(40, 220, 113, 20))
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.lineEdit_Y = QtWidgets.QLineEdit(self.groupBox_XYZ)
        self.lineEdit_Y.setGeometry(QtCore.QRect(40, 250, 113, 20))
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.lineEdit_Z = QtWidgets.QLineEdit(self.groupBox_XYZ)
        self.lineEdit_Z.setGeometry(QtCore.QRect(40, 280, 113, 20))
        self.lineEdit_Z.setObjectName("lineEdit_Z")
        self.label_Xpos = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Xpos.setGeometry(QtCore.QRect(20, 220, 47, 13))
        self.label_Xpos.setObjectName("label_Xpos")
        self.label_Ypos = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Ypos.setGeometry(QtCore.QRect(20, 250, 47, 13))
        self.label_Ypos.setObjectName("label_Ypos")
        self.label_Zpos = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Zpos.setGeometry(QtCore.QRect(20, 280, 47, 13))
        self.label_Zpos.setObjectName("label_Zpos")
        self.groupBox_actPosition = QtWidgets.QGroupBox(self.groupBox_XYZ)
        self.groupBox_actPosition.setGeometry(QtCore.QRect(430, 20, 111, 191))
        self.groupBox_actPosition.setObjectName("groupBox_actPosition")
        self.pushButton_SetPos = QtWidgets.QPushButton(self.groupBox_actPosition)
        self.pushButton_SetPos.setGeometry(QtCore.QRect(10, 120, 91, 61))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/Map-Marker-Push-Pin-1-Right-Chartreuse-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SetPos.setIcon(icon8)
        self.pushButton_SetPos.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_SetPos.setObjectName("pushButton_SetPos")
        self.label_ZactPos = QtWidgets.QLabel(self.groupBox_actPosition)
        self.label_ZactPos.setGeometry(QtCore.QRect(20, 90, 34, 13))
        self.label_ZactPos.setObjectName("label_ZactPos")
        self.label_YactPos = QtWidgets.QLabel(self.groupBox_actPosition)
        self.label_YactPos.setGeometry(QtCore.QRect(20, 60, 34, 13))
        self.label_YactPos.setObjectName("label_YactPos")
        self.label_XactPos = QtWidgets.QLabel(self.groupBox_actPosition)
        self.label_XactPos.setGeometry(QtCore.QRect(20, 30, 34, 13))
        self.label_XactPos.setObjectName("label_XactPos")
        self.pushButton_Go = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_Go.setGeometry(QtCore.QRect(184, 240, 81, 81))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/Alarm-Tick-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Go.setIcon(icon9)
        self.pushButton_Go.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Go.setObjectName("pushButton_Go")
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_Stop.setGeometry(QtCore.QRect(290, 240, 91, 81))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/Button-Pause-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Stop.setIcon(icon10)
        self.pushButton_Stop.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.pushButton_Home = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_Home.setGeometry(QtCore.QRect(440, 270, 91, 23))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/Actions-go-home-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Home.setIcon(icon11)
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton_Reset = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_Reset.setGeometry(QtCore.QRect(440, 300, 91, 23))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("img/Reset-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Reset.setIcon(icon12)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.groupBox_DeltaMove = QtWidgets.QGroupBox(self.groupBox_XYZ)
        self.groupBox_DeltaMove.setGeometry(QtCore.QRect(340, 60, 91, 101))
        self.groupBox_DeltaMove.setObjectName("groupBox_DeltaMove")
        self.label_DeltaZ = QtWidgets.QLabel(self.groupBox_DeltaMove)
        self.label_DeltaZ.setGeometry(QtCore.QRect(10, 70, 16, 20))
        self.label_DeltaZ.setObjectName("label_DeltaZ")
        self.lineEdit_DeltaY = QtWidgets.QLineEdit(self.groupBox_DeltaMove)
        self.lineEdit_DeltaY.setGeometry(QtCore.QRect(20, 46, 61, 20))
        self.lineEdit_DeltaY.setObjectName("lineEdit_DeltaY")
        self.lineEdit_DeltaX = QtWidgets.QLineEdit(self.groupBox_DeltaMove)
        self.lineEdit_DeltaX.setGeometry(QtCore.QRect(20, 20, 61, 20))
        self.lineEdit_DeltaX.setObjectName("lineEdit_DeltaX")
        self.lineEdit_DeltaZ = QtWidgets.QLineEdit(self.groupBox_DeltaMove)
        self.lineEdit_DeltaZ.setGeometry(QtCore.QRect(20, 72, 61, 20))
        self.lineEdit_DeltaZ.setObjectName("lineEdit_DeltaZ")
        self.label_DeltaX = QtWidgets.QLabel(self.groupBox_DeltaMove)
        self.label_DeltaX.setGeometry(QtCore.QRect(10, 20, 6, 20))
        self.label_DeltaX.setObjectName("label_DeltaX")
        self.label_DeltaY = QtWidgets.QLabel(self.groupBox_DeltaMove)
        self.label_DeltaY.setGeometry(QtCore.QRect(10, 50, 16, 16))
        self.label_DeltaY.setObjectName("label_DeltaY")
        self.label_Feedrate = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Feedrate.setGeometry(QtCore.QRect(20, 310, 47, 13))
        self.label_Feedrate.setObjectName("label_Feedrate")
        self.lineEdit_Feedrate = QtWidgets.QLineEdit(self.groupBox_XYZ)
        self.lineEdit_Feedrate.setGeometry(QtCore.QRect(40, 310, 113, 20))
        self.lineEdit_Feedrate.setObjectName("lineEdit_Feedrate")
        self.pushButton_CleanAlarm = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_CleanAlarm.setGeometry(QtCore.QRect(440, 240, 91, 23))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("img/Clear-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_CleanAlarm.setIcon(icon13)
        self.pushButton_CleanAlarm.setObjectName("pushButton_CleanAlarm")
        self.pushButton_XYRU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XYRU.setGeometry(QtCore.QRect(110, 30, 51, 51))
        self.pushButton_XYRU.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon-DiagRU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XYRU.setIcon(icon14)
        self.pushButton_XYRU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XYRU.setObjectName("pushButton_XYRU")
        self.pushButton_XYLU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XYLU.setGeometry(QtCore.QRect(10, 30, 51, 51))
        self.pushButton_XYLU.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon-DiagLU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XYLU.setIcon(icon15)
        self.pushButton_XYLU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XYLU.setObjectName("pushButton_XYLU")
        self.pushButton_XYRD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XYRD.setGeometry(QtCore.QRect(110, 130, 51, 51))
        self.pushButton_XYRD.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon-DiagRD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XYRD.setIcon(icon16)
        self.pushButton_XYRD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XYRD.setObjectName("pushButton_XYRD")
        self.pushButton_XYLD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XYLD.setGeometry(QtCore.QRect(10, 130, 51, 51))
        self.pushButton_XYLD.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon-DiagLD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XYLD.setIcon(icon17)
        self.pushButton_XYLD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XYLD.setObjectName("pushButton_XYLD")
        self.pushButton_XZLU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XZLU.setGeometry(QtCore.QRect(230, 10, 51, 51))
        self.pushButton_XZLU.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_DiagLU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XZLU.setIcon(icon18)
        self.pushButton_XZLU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XZLU.setObjectName("pushButton_XZLU")
        self.pushButton_XZRU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XZRU.setGeometry(QtCore.QRect(280, 10, 51, 51))
        self.pushButton_XZRU.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_DiagRU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XZRU.setIcon(icon19)
        self.pushButton_XZRU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XZRU.setObjectName("pushButton_XZRU")
        self.pushButton_XZLD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XZLD.setGeometry(QtCore.QRect(230, 60, 51, 51))
        self.pushButton_XZLD.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_DiagLD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XZLD.setIcon(icon20)
        self.pushButton_XZLD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XZLD.setObjectName("pushButton_XZLD")
        self.pushButton_XZRD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XZRD.setGeometry(QtCore.QRect(280, 60, 51, 51))
        self.pushButton_XZRD.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_DiagRD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XZRD.setIcon(icon21)
        self.pushButton_XZRD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XZRD.setObjectName("pushButton_XZRD")
        self.label_XZ = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_XZ.setGeometry(QtCore.QRect(270, 50, 31, 20))
        self.label_XZ.setObjectName("label_XZ")
        self.label_Z = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Z.setGeometry(QtCore.QRect(190, 100, 47, 13))
        self.label_Z.setObjectName("label_Z")
        self.label_XY = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_XY.setGeometry(QtCore.QRect(80, 100, 47, 13))
        self.label_XY.setObjectName("label_XY")
        self.pushButton_YZLU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YZLU.setGeometry(QtCore.QRect(230, 120, 51, 51))
        self.pushButton_YZLU.setText("")
        self.pushButton_YZLU.setIcon(icon18)
        self.pushButton_YZLU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YZLU.setObjectName("pushButton_YZLU")
        self.pushButton_YZLD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YZLD.setGeometry(QtCore.QRect(230, 170, 51, 51))
        self.pushButton_YZLD.setText("")
        self.pushButton_YZLD.setIcon(icon20)
        self.pushButton_YZLD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YZLD.setObjectName("pushButton_YZLD")
        self.pushButton_YZRU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YZRU.setGeometry(QtCore.QRect(280, 120, 51, 51))
        self.pushButton_YZRU.setText("")
        self.pushButton_YZRU.setIcon(icon19)
        self.pushButton_YZRU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YZRU.setObjectName("pushButton_YZRU")
        self.pushButton_YZRD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YZRD.setGeometry(QtCore.QRect(280, 170, 51, 51))
        self.pushButton_YZRD.setText("")
        self.pushButton_YZRD.setIcon(icon21)
        self.pushButton_YZRD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YZRD.setObjectName("pushButton_YZRD")
        self.label_YZ = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_YZ.setGeometry(QtCore.QRect(270, 160, 51, 20))
        self.label_YZ.setObjectName("label_YZ")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_Config = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_Config.setGeometry(QtCore.QRect(10, 30, 451, 411))
        self.tableWidget_Config.setObjectName("tableWidget_Config")
        self.tableWidget_Config.setColumnCount(0)
        self.tableWidget_Config.setRowCount(0)
        self.pushButton_SetConfig = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_SetConfig.setGeometry(QtCore.QRect(464, 390, 91, 51))
        self.pushButton_SetConfig.setIcon(icon9)
        self.pushButton_SetConfig.setObjectName("pushButton_SetConfig")
        self.lineEdit_ConfigValue = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_ConfigValue.setGeometry(QtCore.QRect(110, 0, 91, 20))
        self.lineEdit_ConfigValue.setObjectName("lineEdit_ConfigValue")
        self.comboBox_ConfigItem = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_ConfigItem.setGeometry(QtCore.QRect(10, 0, 91, 21))
        self.comboBox_ConfigItem.setObjectName("comboBox_ConfigItem")
        self.label_ConfigInfo = QtWidgets.QLabel(self.tab_2)
        self.label_ConfigInfo.setGeometry(QtCore.QRect(210, 0, 47, 16))
        self.label_ConfigInfo.setObjectName("label_ConfigInfo")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_Gcode = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_Gcode.setGeometry(QtCore.QRect(0, 10, 541, 61))
        self.groupBox_Gcode.setObjectName("groupBox_Gcode")
        self.lineEdit_Gcode = QtWidgets.QLineEdit(self.groupBox_Gcode)
        self.lineEdit_Gcode.setGeometry(QtCore.QRect(10, 20, 441, 20))
        self.lineEdit_Gcode.setObjectName("lineEdit_Gcode")
        self.pushButton_Gcodesend = QtWidgets.QPushButton(self.groupBox_Gcode)
        self.pushButton_Gcodesend.setGeometry(QtCore.QRect(460, 20, 75, 23))
        self.pushButton_Gcodesend.setObjectName("pushButton_Gcodesend")
        self.groupBox_GcodeScript = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_GcodeScript.setGeometry(QtCore.QRect(0, 70, 541, 381))
        self.groupBox_GcodeScript.setObjectName("groupBox_GcodeScript")
        self.pushButton_LoadGcode = QtWidgets.QPushButton(self.groupBox_GcodeScript)
        self.pushButton_LoadGcode.setGeometry(QtCore.QRect(440, 40, 91, 23))
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("img/open-file-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LoadGcode.setIcon(icon22)
        self.pushButton_LoadGcode.setObjectName("pushButton_LoadGcode")
        self.PushButton_RunGcodeScript = QtWidgets.QPushButton(self.groupBox_GcodeScript)
        self.PushButton_RunGcodeScript.setGeometry(QtCore.QRect(454, 350, 81, 23))
        self.PushButton_RunGcodeScript.setObjectName("PushButton_RunGcodeScript")
        self.checkBox_Gcode = QtWidgets.QCheckBox(self.groupBox_GcodeScript)
        self.checkBox_Gcode.setGeometry(QtCore.QRect(450, 320, 91, 20))
        self.checkBox_Gcode.setObjectName("checkBox_Gcode")
        self.pushButton_SaveGcode = QtWidgets.QPushButton(self.groupBox_GcodeScript)
        self.pushButton_SaveGcode.setGeometry(QtCore.QRect(440, 70, 91, 23))
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("img/Floppy-Small-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SaveGcode.setIcon(icon23)
        self.pushButton_SaveGcode.setObjectName("pushButton_SaveGcode")
        self.plaintextEdit_GcodeScript = QtWidgets.QPlainTextEdit(self.groupBox_GcodeScript)
        self.plaintextEdit_GcodeScript.setGeometry(QtCore.QRect(10, 20, 421, 351))
        self.plaintextEdit_GcodeScript.setObjectName("plaintextEdit_GcodeScript")
        self.frame_GcodePauseStop = QtWidgets.QFrame(self.groupBox_GcodeScript)
        self.frame_GcodePauseStop.setGeometry(QtCore.QRect(430, 170, 111, 111))
        self.frame_GcodePauseStop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_GcodePauseStop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_GcodePauseStop.setObjectName("frame_GcodePauseStop")
        self.pushButton_Hold_Start_Gcode = QtWidgets.QPushButton(self.frame_GcodePauseStop)
        self.pushButton_Hold_Start_Gcode.setGeometry(QtCore.QRect(20, 10, 81, 41))
        self.pushButton_Hold_Start_Gcode.setIcon(icon10)
        self.pushButton_Hold_Start_Gcode.setObjectName("pushButton_Hold_Start_Gcode")
        self.pushButton_StopGcode = QtWidgets.QPushButton(self.frame_GcodePauseStop)
        self.pushButton_StopGcode.setGeometry(QtCore.QRect(20, 60, 81, 41))
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("img/Actions-process-stop-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_StopGcode.setIcon(icon24)
        self.pushButton_StopGcode.setObjectName("pushButton_StopGcode")
        self.tabWidget.addTab(self.tab_3, "")
        self.pushButton_Emergency = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Emergency.setGeometry(QtCore.QRect(490, 520, 71, 61))
        self.pushButton_Emergency.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("img/Perspective-Button-Shutdown-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Emergency.setIcon(icon25)
        self.pushButton_Emergency.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_Emergency.setFlat(True)
        self.pushButton_Emergency.setObjectName("pushButton_Emergency")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 564, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfig = QtWidgets.QMenu(self.menuFile)
        self.menuConfig.setObjectName("menuConfig")
        self.menuGcode = QtWidgets.QMenu(self.menuFile)
        self.menuGcode.setObjectName("menuGcode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_Config = QtWidgets.QAction(MainWindow)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.actionLoad_Gcode = QtWidgets.QAction(MainWindow)
        self.actionLoad_Gcode.setObjectName("actionLoad_Gcode")
        self.actionSave_Gcode = QtWidgets.QAction(MainWindow)
        self.actionSave_Gcode.setObjectName("actionSave_Gcode")
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.actionSave_Config)
        self.menuGcode.addAction(self.actionLoad_Gcode)
        self.menuGcode.addAction(self.actionSave_Gcode)
        self.menuFile.addAction(self.menuConfig.menuAction())
        self.menuFile.addAction(self.menuGcode.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XYZ Mover by FG"))
        self.groupBoxConnect.setTitle(_translate("MainWindow", "Connect"))
        self.pushButton_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.label_COM.setText(_translate("MainWindow", "COM Port"))
        self.label_ConnSpeed.setText(_translate("MainWindow", "Connection Speed"))
        self.pushButton_Connect.setText(_translate("MainWindow", "Connect"))
        self.groupBox_XYZ.setTitle(_translate("MainWindow", "XYZ Mover"))
        self.label_Xpos.setText(_translate("MainWindow", "X"))
        self.label_Ypos.setText(_translate("MainWindow", "Y"))
        self.label_Zpos.setText(_translate("MainWindow", "Z "))
        self.groupBox_actPosition.setTitle(_translate("MainWindow", "Actual Position"))
        self.pushButton_SetPos.setText(_translate("MainWindow", "Set"))
        self.label_ZactPos.setText(_translate("MainWindow", "Z=  NA"))
        self.label_YactPos.setText(_translate("MainWindow", "Y=  NA"))
        self.label_XactPos.setText(_translate("MainWindow", "X=  NA"))
        self.pushButton_Go.setText(_translate("MainWindow", "GO"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Hold"))
        self.pushButton_Home.setText(_translate("MainWindow", "Home"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset Signal"))
        self.groupBox_DeltaMove.setTitle(_translate("MainWindow", "Delta"))
        self.label_DeltaZ.setText(_translate("MainWindow", "Z"))
        self.label_DeltaX.setText(_translate("MainWindow", "X"))
        self.label_DeltaY.setText(_translate("MainWindow", "Y"))
        self.label_Feedrate.setText(_translate("MainWindow", "F"))
        self.pushButton_CleanAlarm.setText(_translate("MainWindow", "Clear Alarm"))
        self.label_XZ.setText(_translate("MainWindow", "  XZ"))
        self.label_Z.setText(_translate("MainWindow", "Z"))
        self.label_XY.setText(_translate("MainWindow", "XY"))
        self.label_YZ.setText(_translate("MainWindow", "  YZ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Move"))
        self.pushButton_SetConfig.setText(_translate("MainWindow", "Set Value"))
        self.label_ConfigInfo.setText(_translate("MainWindow", "NA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Config"))
        self.groupBox_Gcode.setTitle(_translate("MainWindow", "Gcode input"))
        self.pushButton_Gcodesend.setText(_translate("MainWindow", "Gcode Send"))
        self.groupBox_GcodeScript.setTitle(_translate("MainWindow", "Gcode Script"))
        self.pushButton_LoadGcode.setText(_translate("MainWindow", "Load Gcode"))
        self.PushButton_RunGcodeScript.setText(_translate("MainWindow", "Run Gcode"))
        self.checkBox_Gcode.setText(_translate("MainWindow", "Check Gcode"))
        self.pushButton_SaveGcode.setText(_translate("MainWindow", "Save Gcode"))
        self.pushButton_Hold_Start_Gcode.setText(_translate("MainWindow", "Pause"))
        self.pushButton_StopGcode.setText(_translate("MainWindow", "STOP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Gcode"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConfig.setTitle(_translate("MainWindow", "Config"))
        self.menuGcode.setTitle(_translate("MainWindow", "Gcode"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_Config.setText(_translate("MainWindow", "Save Config"))
        self.actionLoad_Gcode.setText(_translate("MainWindow", "Load Gcode"))
        self.actionSave_Gcode.setText(_translate("MainWindow", "Save Gcode "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
