# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiXYZ_VariableButtonDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_VBDD(object):
    def setupUi(self, Dialog_VBDD):
        Dialog_VBDD.setObjectName("Dialog_VBDD")
        Dialog_VBDD.resize(428, 586)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_VBDD)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_VBDF = QtWidgets.QTabWidget(Dialog_VBDD)
        self.tabWidget_VBDF.setObjectName("tabWidget_VBDF")
        self.tabWidget_VBDFPage1 = QtWidgets.QWidget()
        self.tabWidget_VBDFPage1.setObjectName("tabWidget_VBDFPage1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabWidget_VBDFPage1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_VBDD_id = QtWidgets.QLabel(self.tabWidget_VBDFPage1)
        self.label_VBDD_id.setObjectName("label_VBDD_id")
        self.horizontalLayout_4.addWidget(self.label_VBDD_id)
        self.pushButton_VBDD_Icon = QtWidgets.QPushButton(self.tabWidget_VBDFPage1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Actions-arrow-up-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBDD_Icon.setIcon(icon)
        self.pushButton_VBDD_Icon.setObjectName("pushButton_VBDD_Icon")
        self.horizontalLayout_4.addWidget(self.pushButton_VBDD_Icon)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_VBDD_batton_type = QtWidgets.QLabel(self.tabWidget_VBDFPage1)
        self.label_VBDD_batton_type.setObjectName("label_VBDD_batton_type")
        self.horizontalLayout_7.addWidget(self.label_VBDD_batton_type)
        self.comboBox_VBDD_batton_type = QtWidgets.QComboBox(self.tabWidget_VBDFPage1)
        self.comboBox_VBDD_batton_type.setObjectName("comboBox_VBDD_batton_type")
        self.horizontalLayout_7.addWidget(self.comboBox_VBDD_batton_type)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_VBDD_Name = QtWidgets.QLabel(self.tabWidget_VBDFPage1)
        self.label_VBDD_Name.setObjectName("label_VBDD_Name")
        self.horizontalLayout.addWidget(self.label_VBDD_Name)
        self.lineEdit_VBDD_Name = QtWidgets.QLineEdit(self.tabWidget_VBDFPage1)
        self.lineEdit_VBDD_Name.setObjectName("lineEdit_VBDD_Name")
        self.horizontalLayout.addWidget(self.lineEdit_VBDD_Name)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.groupBox_VBDD_byaction = QtWidgets.QGroupBox(self.tabWidget_VBDFPage1)
        self.groupBox_VBDD_byaction.setCheckable(True)
        self.groupBox_VBDD_byaction.setObjectName("groupBox_VBDD_byaction")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_VBDD_byaction)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_VBDD_CHid = QtWidgets.QLabel(self.groupBox_VBDD_byaction)
        self.label_VBDD_CHid.setObjectName("label_VBDD_CHid")
        self.horizontalLayout_3.addWidget(self.label_VBDD_CHid)
        self.label_VBDD_Force_id = QtWidgets.QLabel(self.groupBox_VBDD_byaction)
        self.label_VBDD_Force_id.setObjectName("label_VBDD_Force_id")
        self.horizontalLayout_3.addWidget(self.label_VBDD_Force_id)
        self.comboBox_VBDD_CHid = QtWidgets.QComboBox(self.groupBox_VBDD_byaction)
        self.comboBox_VBDD_CHid.setObjectName("comboBox_VBDD_CHid")
        self.horizontalLayout_3.addWidget(self.comboBox_VBDD_CHid)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_VBDD_action = QtWidgets.QLabel(self.groupBox_VBDD_byaction)
        self.label_VBDD_action.setObjectName("label_VBDD_action")
        self.horizontalLayout_2.addWidget(self.label_VBDD_action)
        self.comboBox_VBDD_action = QtWidgets.QComboBox(self.groupBox_VBDD_byaction)
        self.comboBox_VBDD_action.setObjectName("comboBox_VBDD_action")
        self.horizontalLayout_2.addWidget(self.comboBox_VBDD_action)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.groupBox_VBDD_Parameters = QtWidgets.QGroupBox(self.groupBox_VBDD_byaction)
        self.groupBox_VBDD_Parameters.setCheckable(True)
        self.groupBox_VBDD_Parameters.setObjectName("groupBox_VBDD_Parameters")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_Parameters)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_VBDD_parameters = QtWidgets.QTableWidget(self.groupBox_VBDD_Parameters)
        self.tableWidget_VBDD_parameters.setObjectName("tableWidget_VBDD_parameters")
        self.tableWidget_VBDD_parameters.setColumnCount(0)
        self.tableWidget_VBDD_parameters.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_VBDD_parameters)
        self.gridLayout_2.addWidget(self.groupBox_VBDD_Parameters, 4, 0, 2, 1)
        self.verticalLayout_6.addWidget(self.groupBox_VBDD_byaction)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_VBDD_Format = QtWidgets.QLabel(self.tabWidget_VBDFPage1)
        self.label_VBDD_Format.setObjectName("label_VBDD_Format")
        self.verticalLayout_2.addWidget(self.label_VBDD_Format)
        self.label_VBDD_Result = QtWidgets.QLabel(self.tabWidget_VBDFPage1)
        self.label_VBDD_Result.setObjectName("label_VBDD_Result")
        self.verticalLayout_2.addWidget(self.label_VBDD_Result)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.groupBox_VBDD_byGcode = QtWidgets.QGroupBox(self.tabWidget_VBDFPage1)
        self.groupBox_VBDD_byGcode.setCheckable(True)
        self.groupBox_VBDD_byGcode.setChecked(False)
        self.groupBox_VBDD_byGcode.setObjectName("groupBox_VBDD_byGcode")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_byGcode)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit_VBDD_Gcode = QtWidgets.QPlainTextEdit(self.groupBox_VBDD_byGcode)
        self.plainTextEdit_VBDD_Gcode.setObjectName("plainTextEdit_VBDD_Gcode")
        self.verticalLayout_3.addWidget(self.plainTextEdit_VBDD_Gcode)
        self.verticalLayout_6.addWidget(self.groupBox_VBDD_byGcode)
        self.groupBox_VBDD_byScript = QtWidgets.QGroupBox(self.tabWidget_VBDFPage1)
        self.groupBox_VBDD_byScript.setCheckable(True)
        self.groupBox_VBDD_byScript.setChecked(False)
        self.groupBox_VBDD_byScript.setObjectName("groupBox_VBDD_byScript")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_VBDD_byScript)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_VBDD_Script = QtWidgets.QLabel(self.groupBox_VBDD_byScript)
        self.label_VBDD_Script.setObjectName("label_VBDD_Script")
        self.horizontalLayout_5.addWidget(self.label_VBDD_Script)
        self.pushButton_VBDD_Script = QtWidgets.QPushButton(self.groupBox_VBDD_byScript)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/Document-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBDD_Script.setIcon(icon1)
        self.pushButton_VBDD_Script.setObjectName("pushButton_VBDD_Script")
        self.horizontalLayout_5.addWidget(self.pushButton_VBDD_Script)
        self.verticalLayout_6.addWidget(self.groupBox_VBDD_byScript)
        self.tabWidget_VBDF.addTab(self.tabWidget_VBDFPage1, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_VBDD_id_2 = QtWidgets.QLabel(self.tab)
        self.label_VBDD_id_2.setObjectName("label_VBDD_id_2")
        self.horizontalLayout_8.addWidget(self.label_VBDD_id_2)
        self.pushButton_VBDD_Icon_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_VBDD_Icon_2.setIcon(icon)
        self.pushButton_VBDD_Icon_2.setObjectName("pushButton_VBDD_Icon_2")
        self.horizontalLayout_8.addWidget(self.pushButton_VBDD_Icon_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_VBDD_batton_type_2 = QtWidgets.QLabel(self.tab)
        self.label_VBDD_batton_type_2.setObjectName("label_VBDD_batton_type_2")
        self.horizontalLayout_11.addWidget(self.label_VBDD_batton_type_2)
        self.comboBox_VBDD_batton_type_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_VBDD_batton_type_2.setObjectName("comboBox_VBDD_batton_type_2")
        self.horizontalLayout_11.addWidget(self.comboBox_VBDD_batton_type_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.groupBox_VBDD_byaction_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_VBDD_byaction_2.setCheckable(True)
        self.groupBox_VBDD_byaction_2.setObjectName("groupBox_VBDD_byaction_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_VBDD_byaction_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_VBDD_CHid_2 = QtWidgets.QLabel(self.groupBox_VBDD_byaction_2)
        self.label_VBDD_CHid_2.setObjectName("label_VBDD_CHid_2")
        self.horizontalLayout_9.addWidget(self.label_VBDD_CHid_2)
        self.label_VBDD_Force_id_2 = QtWidgets.QLabel(self.groupBox_VBDD_byaction_2)
        self.label_VBDD_Force_id_2.setObjectName("label_VBDD_Force_id_2")
        self.horizontalLayout_9.addWidget(self.label_VBDD_Force_id_2)
        self.comboBox_VBDD_CHid_2 = QtWidgets.QComboBox(self.groupBox_VBDD_byaction_2)
        self.comboBox_VBDD_CHid_2.setObjectName("comboBox_VBDD_CHid_2")
        self.horizontalLayout_9.addWidget(self.comboBox_VBDD_CHid_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_VBDD_action_2 = QtWidgets.QLabel(self.groupBox_VBDD_byaction_2)
        self.label_VBDD_action_2.setObjectName("label_VBDD_action_2")
        self.horizontalLayout_10.addWidget(self.label_VBDD_action_2)
        self.comboBox_VBDD_action_2 = QtWidgets.QComboBox(self.groupBox_VBDD_byaction_2)
        self.comboBox_VBDD_action_2.setObjectName("comboBox_VBDD_action_2")
        self.horizontalLayout_10.addWidget(self.comboBox_VBDD_action_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.groupBox_VBDD_Parameters_2 = QtWidgets.QGroupBox(self.groupBox_VBDD_byaction_2)
        self.groupBox_VBDD_Parameters_2.setCheckable(True)
        self.groupBox_VBDD_Parameters_2.setObjectName("groupBox_VBDD_Parameters_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_Parameters_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_VBDD_parameters_2 = QtWidgets.QTableWidget(self.groupBox_VBDD_Parameters_2)
        self.tableWidget_VBDD_parameters_2.setObjectName("tableWidget_VBDD_parameters_2")
        self.tableWidget_VBDD_parameters_2.setColumnCount(0)
        self.tableWidget_VBDD_parameters_2.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_VBDD_parameters_2)
        self.gridLayout_3.addWidget(self.groupBox_VBDD_Parameters_2, 4, 0, 2, 1)
        self.verticalLayout_9.addWidget(self.groupBox_VBDD_byaction_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_VBDD_Format_2 = QtWidgets.QLabel(self.tab)
        self.label_VBDD_Format_2.setObjectName("label_VBDD_Format_2")
        self.verticalLayout_7.addWidget(self.label_VBDD_Format_2)
        self.label_VBDD_Result_2 = QtWidgets.QLabel(self.tab)
        self.label_VBDD_Result_2.setObjectName("label_VBDD_Result_2")
        self.verticalLayout_7.addWidget(self.label_VBDD_Result_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.groupBox_VBDD_byGcode_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_VBDD_byGcode_2.setCheckable(True)
        self.groupBox_VBDD_byGcode_2.setChecked(False)
        self.groupBox_VBDD_byGcode_2.setObjectName("groupBox_VBDD_byGcode_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_byGcode_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plainTextEdit_VBDD_Gcode_2 = QtWidgets.QPlainTextEdit(self.groupBox_VBDD_byGcode_2)
        self.plainTextEdit_VBDD_Gcode_2.setObjectName("plainTextEdit_VBDD_Gcode_2")
        self.verticalLayout_8.addWidget(self.plainTextEdit_VBDD_Gcode_2)
        self.verticalLayout_9.addWidget(self.groupBox_VBDD_byGcode_2)
        self.groupBox_VBDD_byScript_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_VBDD_byScript_2.setCheckable(True)
        self.groupBox_VBDD_byScript_2.setChecked(False)
        self.groupBox_VBDD_byScript_2.setObjectName("groupBox_VBDD_byScript_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_VBDD_byScript_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_VBDD_Script_2 = QtWidgets.QLabel(self.groupBox_VBDD_byScript_2)
        self.label_VBDD_Script_2.setObjectName("label_VBDD_Script_2")
        self.horizontalLayout_6.addWidget(self.label_VBDD_Script_2)
        self.pushButton_VBDD_Script_2 = QtWidgets.QPushButton(self.groupBox_VBDD_byScript_2)
        self.pushButton_VBDD_Script_2.setIcon(icon1)
        self.pushButton_VBDD_Script_2.setObjectName("pushButton_VBDD_Script_2")
        self.horizontalLayout_6.addWidget(self.pushButton_VBDD_Script_2)
        self.verticalLayout_9.addWidget(self.groupBox_VBDD_byScript_2)
        self.tabWidget_VBDF.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget_VBDF)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_VBDD)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_VBDD)
        self.tabWidget_VBDF.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog_VBDD.accept)
        self.buttonBox.rejected.connect(Dialog_VBDD.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_VBDD)

    def retranslateUi(self, Dialog_VBDD):
        _translate = QtCore.QCoreApplication.translate
        Dialog_VBDD.setWindowTitle(_translate("Dialog_VBDD", "Variable Button Data Dialog"))
        self.label_VBDD_id.setText(_translate("Dialog_VBDD", "Id:"))
        self.pushButton_VBDD_Icon.setText(_translate("Dialog_VBDD", "Select Icon"))
        self.label_VBDD_batton_type.setText(_translate("Dialog_VBDD", "Batton Type:"))
        self.label_VBDD_Name.setText(_translate("Dialog_VBDD", "Name:"))
        self.groupBox_VBDD_byaction.setTitle(_translate("Dialog_VBDD", "By action"))
        self.label_VBDD_CHid.setText(_translate("Dialog_VBDD", "Force Id"))
        self.label_VBDD_Force_id.setText(_translate("Dialog_VBDD", "Force interface to:"))
        self.label_VBDD_action.setText(_translate("Dialog_VBDD", "Action"))
        self.groupBox_VBDD_Parameters.setTitle(_translate("Dialog_VBDD", "Show Parameters"))
        self.label_VBDD_Format.setText(_translate("Dialog_VBDD", "Action Format"))
        self.label_VBDD_Result.setText(_translate("Dialog_VBDD", "Action Result"))
        self.groupBox_VBDD_byGcode.setToolTip(_translate("Dialog_VBDD", "To send Gcode no action has to be selected."))
        self.groupBox_VBDD_byGcode.setTitle(_translate("Dialog_VBDD", "By Gcode"))
        self.groupBox_VBDD_byScript.setToolTip(_translate("Dialog_VBDD", "To send script no action and no Gcode must be present."))
        self.groupBox_VBDD_byScript.setTitle(_translate("Dialog_VBDD", "By Script"))
        self.label_VBDD_Script.setText(_translate("Dialog_VBDD", "No Script Selected"))
        self.pushButton_VBDD_Script.setText(_translate("Dialog_VBDD", "PushButton"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tabWidget_VBDFPage1), _translate("Dialog_VBDD", "First State"))
        self.label_VBDD_id_2.setText(_translate("Dialog_VBDD", "Id:"))
        self.pushButton_VBDD_Icon_2.setText(_translate("Dialog_VBDD", "Select Icon"))
        self.label_VBDD_batton_type_2.setText(_translate("Dialog_VBDD", "Batton Type:"))
        self.groupBox_VBDD_byaction_2.setTitle(_translate("Dialog_VBDD", "By action"))
        self.label_VBDD_CHid_2.setText(_translate("Dialog_VBDD", "Force Id"))
        self.label_VBDD_Force_id_2.setText(_translate("Dialog_VBDD", "Force interface to:"))
        self.label_VBDD_action_2.setText(_translate("Dialog_VBDD", "Action"))
        self.groupBox_VBDD_Parameters_2.setTitle(_translate("Dialog_VBDD", "Show Parameters"))
        self.label_VBDD_Format_2.setText(_translate("Dialog_VBDD", "Action Format"))
        self.label_VBDD_Result_2.setText(_translate("Dialog_VBDD", "Action Result"))
        self.groupBox_VBDD_byGcode_2.setToolTip(_translate("Dialog_VBDD", "To send Gcode no action has to be selected."))
        self.groupBox_VBDD_byGcode_2.setTitle(_translate("Dialog_VBDD", "By Gcode"))
        self.groupBox_VBDD_byScript_2.setToolTip(_translate("Dialog_VBDD", "To send script no action and no Gcode must be present."))
        self.groupBox_VBDD_byScript_2.setTitle(_translate("Dialog_VBDD", "By Script"))
        self.label_VBDD_Script_2.setText(_translate("Dialog_VBDD", "No Script Selected"))
        self.pushButton_VBDD_Script_2.setText(_translate("Dialog_VBDD", "PushButton"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tab), _translate("Dialog_VBDD", "Second State"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_VBDD = QtWidgets.QDialog()
    ui = Ui_Dialog_VBDD()
    ui.setupUi(Dialog_VBDD)
    Dialog_VBDD.show()
    sys.exit(app.exec_())
