# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiXYZ_V1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout.addLayout(self.gridLayout_9)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 250))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 9, 324, 130))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.groupBoxConnect = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBoxConnect.setObjectName("groupBoxConnect")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxConnect)
        self.formLayout.setObjectName("formLayout")
        self.label_COM = QtWidgets.QLabel(self.groupBoxConnect)
        self.label_COM.setObjectName("label_COM")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_COM)
        self.comboBox_COM = QtWidgets.QComboBox(self.groupBoxConnect)
        self.comboBox_COM.setObjectName("comboBox_COM")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_COM)
        self.label_ConnSpeed = QtWidgets.QLabel(self.groupBoxConnect)
        self.label_ConnSpeed.setObjectName("label_ConnSpeed")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_ConnSpeed)
        self.comboBox_ConnSpeed = QtWidgets.QComboBox(self.groupBoxConnect)
        self.comboBox_ConnSpeed.setCurrentText("")
        self.comboBox_ConnSpeed.setObjectName("comboBox_ConnSpeed")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_ConnSpeed)
        self.pushButton_Refresh = QtWidgets.QPushButton(self.groupBoxConnect)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Actions-view-refresh-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Refresh.setIcon(icon)
        self.pushButton_Refresh.setObjectName("pushButton_Refresh")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_Refresh)
        self.pushButton_Connect = QtWidgets.QPushButton(self.groupBoxConnect)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/connect-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Connect.setIcon(icon1)
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pushButton_Connect)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.groupBoxConnect)
        self.label_ConnectedStatus = QtWidgets.QLabel(self.layoutWidget)
        self.label_ConnectedStatus.setEnabled(True)
        self.label_ConnectedStatus.setText("")
        self.label_ConnectedStatus.setPixmap(QtGui.QPixmap("img/connect-icon.png"))
        self.label_ConnectedStatus.setScaledContents(True)
        self.label_ConnectedStatus.setObjectName("label_ConnectedStatus")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_ConnectedStatus)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_XYZ = QtWidgets.QGroupBox(self.tab)
        self.groupBox_XYZ.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_XYZ.sizePolicy().hasHeightForWidth())
        self.groupBox_XYZ.setSizePolicy(sizePolicy)
        self.groupBox_XYZ.setObjectName("groupBox_XYZ")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_XYZ)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_YDown = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YDown.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/Actions-go-Down-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_YDown.setIcon(icon2)
        self.pushButton_YDown.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YDown.setObjectName("pushButton_YDown")
        self.gridLayout.addWidget(self.pushButton_YDown, 2, 1, 1, 1)
        self.pushButton_XYLU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XYLU.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon-DiagLU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XYLU.setIcon(icon3)
        self.pushButton_XYLU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XYLU.setObjectName("pushButton_XYLU")
        self.gridLayout.addWidget(self.pushButton_XYLU, 0, 0, 1, 1)
        self.pushButton_YUp = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YUp.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/Actions-go-Up-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_YUp.setIcon(icon4)
        self.pushButton_YUp.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YUp.setObjectName("pushButton_YUp")
        self.gridLayout.addWidget(self.pushButton_YUp, 0, 1, 1, 1)
        self.pushButton_XLeft = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XLeft.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/Actions-go-Left-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XLeft.setIcon(icon5)
        self.pushButton_XLeft.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XLeft.setObjectName("pushButton_XLeft")
        self.gridLayout.addWidget(self.pushButton_XLeft, 1, 0, 1, 1)
        self.pushButton_XRight = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XRight.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XRight.setIcon(icon6)
        self.pushButton_XRight.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XRight.setObjectName("pushButton_XRight")
        self.gridLayout.addWidget(self.pushButton_XRight, 1, 2, 1, 1)
        self.pushButton_XYRU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XYRU.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon-DiagRU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XYRU.setIcon(icon7)
        self.pushButton_XYRU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XYRU.setObjectName("pushButton_XYRU")
        self.gridLayout.addWidget(self.pushButton_XYRU, 0, 2, 1, 1)
        self.pushButton_XYLD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XYLD.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon-DiagLD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XYLD.setIcon(icon8)
        self.pushButton_XYLD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XYLD.setObjectName("pushButton_XYLD")
        self.gridLayout.addWidget(self.pushButton_XYLD, 2, 0, 1, 1)
        self.label_XY = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_XY.setAlignment(QtCore.Qt.AlignCenter)
        self.label_XY.setObjectName("label_XY")
        self.gridLayout.addWidget(self.label_XY, 1, 1, 1, 1)
        self.pushButton_XYRD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XYRD.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/Actions-go-next-icon-DiagRD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_XYRD.setIcon(icon9)
        self.pushButton_XYRD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XYRD.setObjectName("pushButton_XYRD")
        self.gridLayout.addWidget(self.pushButton_XYRD, 2, 2, 1, 1)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_ZUp = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_ZUp.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_ZUp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZUp.setIcon(icon10)
        self.pushButton_ZUp.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_ZUp.setObjectName("pushButton_ZUp")
        self.verticalLayout_2.addWidget(self.pushButton_ZUp)
        self.label_Z = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Z.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Z.setObjectName("label_Z")
        self.verticalLayout_2.addWidget(self.label_Z)
        self.pushButton_ZDown = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_ZDown.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_Zdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_ZDown.setIcon(icon11)
        self.pushButton_ZDown.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_ZDown.setObjectName("pushButton_ZDown")
        self.verticalLayout_2.addWidget(self.pushButton_ZDown)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.verticalLayout_2)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_YZ = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_YZ.setAlignment(QtCore.Qt.AlignCenter)
        self.label_YZ.setObjectName("label_YZ")
        self.verticalLayout_4.addWidget(self.label_YZ)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_YZLU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YZLU.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_DiagLU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_YZLU.setIcon(icon12)
        self.pushButton_YZLU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YZLU.setObjectName("pushButton_YZLU")
        self.gridLayout_3.addWidget(self.pushButton_YZLU, 0, 0, 1, 1)
        self.pushButton_YZLD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YZLD.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_DiagLD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_YZLD.setIcon(icon13)
        self.pushButton_YZLD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YZLD.setObjectName("pushButton_YZLD")
        self.gridLayout_3.addWidget(self.pushButton_YZLD, 1, 0, 1, 1)
        self.pushButton_YZRU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YZRU.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_DiagRU.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_YZRU.setIcon(icon14)
        self.pushButton_YZRU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YZRU.setObjectName("pushButton_YZRU")
        self.gridLayout_3.addWidget(self.pushButton_YZRU, 0, 1, 1, 1)
        self.pushButton_YZRD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_YZRD.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("img/Actions-go-next-view-icon_DiagRD.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_YZRD.setIcon(icon15)
        self.pushButton_YZRD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_YZRD.setObjectName("pushButton_YZRD")
        self.gridLayout_3.addWidget(self.pushButton_YZRD, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_XZ = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_XZ.setAlignment(QtCore.Qt.AlignCenter)
        self.label_XZ.setObjectName("label_XZ")
        self.verticalLayout_3.addWidget(self.label_XZ)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_XZLU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XZLU.setText("")
        self.pushButton_XZLU.setIcon(icon12)
        self.pushButton_XZLU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XZLU.setObjectName("pushButton_XZLU")
        self.gridLayout_2.addWidget(self.pushButton_XZLU, 0, 0, 1, 1)
        self.pushButton_XZRU = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XZRU.setText("")
        self.pushButton_XZRU.setIcon(icon14)
        self.pushButton_XZRU.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XZRU.setObjectName("pushButton_XZRU")
        self.gridLayout_2.addWidget(self.pushButton_XZRU, 0, 1, 1, 1)
        self.pushButton_XZLD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XZLD.setText("")
        self.pushButton_XZLD.setIcon(icon13)
        self.pushButton_XZLD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XZLD.setObjectName("pushButton_XZLD")
        self.gridLayout_2.addWidget(self.pushButton_XZLD, 1, 0, 1, 1)
        self.pushButton_XZRD = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_XZRD.setText("")
        self.pushButton_XZRD.setIcon(icon15)
        self.pushButton_XZRD.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_XZRD.setObjectName("pushButton_XZRD")
        self.gridLayout_2.addWidget(self.pushButton_XZRD, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_14.addLayout(self.horizontalLayout_3, 0, 0, 2, 3)
        self.groupBox_actPosition = QtWidgets.QGroupBox(self.groupBox_XYZ)
        self.groupBox_actPosition.setObjectName("groupBox_actPosition")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_actPosition)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_XactPos = QtWidgets.QLabel(self.groupBox_actPosition)
        self.label_XactPos.setObjectName("label_XactPos")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_XactPos)
        self.label_YactPos = QtWidgets.QLabel(self.groupBox_actPosition)
        self.label_YactPos.setObjectName("label_YactPos")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_YactPos)
        self.label_ZactPos = QtWidgets.QLabel(self.groupBox_actPosition)
        self.label_ZactPos.setObjectName("label_ZactPos")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_ZactPos)
        self.pushButton_SetPos = QtWidgets.QPushButton(self.groupBox_actPosition)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("img/Map-Marker-Push-Pin-1-Right-Chartreuse-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SetPos.setIcon(icon16)
        self.pushButton_SetPos.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_SetPos.setObjectName("pushButton_SetPos")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_SetPos)
        self.label_Stateact = QtWidgets.QLabel(self.groupBox_actPosition)
        self.label_Stateact.setObjectName("label_Stateact")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_Stateact)
        self.gridLayout_14.addWidget(self.groupBox_actPosition, 0, 3, 1, 1)
        self.groupBox_DeltaMove = QtWidgets.QGroupBox(self.groupBox_XYZ)
        self.groupBox_DeltaMove.setObjectName("groupBox_DeltaMove")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_DeltaMove)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_DeltaX = QtWidgets.QLabel(self.groupBox_DeltaMove)
        self.label_DeltaX.setObjectName("label_DeltaX")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_DeltaX)
        self.lineEdit_DeltaX = QtWidgets.QLineEdit(self.groupBox_DeltaMove)
        self.lineEdit_DeltaX.setObjectName("lineEdit_DeltaX")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_DeltaX)
        self.label_DeltaY = QtWidgets.QLabel(self.groupBox_DeltaMove)
        self.label_DeltaY.setObjectName("label_DeltaY")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_DeltaY)
        self.lineEdit_DeltaY = QtWidgets.QLineEdit(self.groupBox_DeltaMove)
        self.lineEdit_DeltaY.setObjectName("lineEdit_DeltaY")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_DeltaY)
        self.label_DeltaZ = QtWidgets.QLabel(self.groupBox_DeltaMove)
        self.label_DeltaZ.setObjectName("label_DeltaZ")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_DeltaZ)
        self.lineEdit_DeltaZ = QtWidgets.QLineEdit(self.groupBox_DeltaMove)
        self.lineEdit_DeltaZ.setObjectName("lineEdit_DeltaZ")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_DeltaZ)
        self.gridLayout_14.addWidget(self.groupBox_DeltaMove, 1, 3, 2, 1)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_Xpos = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Xpos.setObjectName("label_Xpos")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Xpos)
        self.lineEdit_X = QtWidgets.QLineEdit(self.groupBox_XYZ)
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_X)
        self.label_Ypos = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Ypos.setObjectName("label_Ypos")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Ypos)
        self.lineEdit_Y = QtWidgets.QLineEdit(self.groupBox_XYZ)
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Y)
        self.label_Zpos = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Zpos.setObjectName("label_Zpos")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Zpos)
        self.lineEdit_Z = QtWidgets.QLineEdit(self.groupBox_XYZ)
        self.lineEdit_Z.setObjectName("lineEdit_Z")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Z)
        self.label_Feedrate = QtWidgets.QLabel(self.groupBox_XYZ)
        self.label_Feedrate.setObjectName("label_Feedrate")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_Feedrate)
        self.lineEdit_Feedrate = QtWidgets.QLineEdit(self.groupBox_XYZ)
        self.lineEdit_Feedrate.setObjectName("lineEdit_Feedrate")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Feedrate)
        self.gridLayout_14.addLayout(self.formLayout_6, 2, 0, 2, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_Go = QtWidgets.QPushButton(self.groupBox_XYZ)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("img/Alarm-Tick-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Go.setIcon(icon17)
        self.pushButton_Go.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Go.setObjectName("pushButton_Go")
        self.gridLayout_4.addWidget(self.pushButton_Go, 0, 0, 1, 1)
        self.pushButton_Pause_Resume = QtWidgets.QPushButton(self.groupBox_XYZ)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("img/Button-Pause-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Pause_Resume.setIcon(icon18)
        self.pushButton_Pause_Resume.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_Pause_Resume.setObjectName("pushButton_Pause_Resume")
        self.gridLayout_4.addWidget(self.pushButton_Pause_Resume, 0, 1, 1, 1)
        self.pushButton_MoveStop = QtWidgets.QPushButton(self.groupBox_XYZ)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("img/Actions-process-stop-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_MoveStop.setIcon(icon19)
        self.pushButton_MoveStop.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_MoveStop.setObjectName("pushButton_MoveStop")
        self.gridLayout_4.addWidget(self.pushButton_MoveStop, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_4, 2, 1, 2, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_CleanAlarm = QtWidgets.QPushButton(self.groupBox_XYZ)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("img/Clear-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_CleanAlarm.setIcon(icon20)
        self.pushButton_CleanAlarm.setObjectName("pushButton_CleanAlarm")
        self.verticalLayout_5.addWidget(self.pushButton_CleanAlarm)
        self.pushButton_Home = QtWidgets.QPushButton(self.groupBox_XYZ)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("img/Actions-go-home-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Home.setIcon(icon21)
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.verticalLayout_5.addWidget(self.pushButton_Home)
        self.pushButton_Reset = QtWidgets.QPushButton(self.groupBox_XYZ)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("img/Reset-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Reset.setIcon(icon22)
        self.pushButton_Reset.setObjectName("pushButton_Reset")
        self.verticalLayout_5.addWidget(self.pushButton_Reset)
        self.gridLayout_14.addLayout(self.verticalLayout_5, 2, 2, 2, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_Home_X = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_Home_X.setIcon(icon21)
        self.pushButton_Home_X.setObjectName("pushButton_Home_X")
        self.gridLayout_5.addWidget(self.pushButton_Home_X, 0, 0, 1, 1)
        self.pushButton_Home_Y = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_Home_Y.setIcon(icon21)
        self.pushButton_Home_Y.setObjectName("pushButton_Home_Y")
        self.gridLayout_5.addWidget(self.pushButton_Home_Y, 0, 1, 1, 1)
        self.pushButton_Home_Z = QtWidgets.QPushButton(self.groupBox_XYZ)
        self.pushButton_Home_Z.setIcon(icon21)
        self.pushButton_Home_Z.setObjectName("pushButton_Home_Z")
        self.gridLayout_5.addWidget(self.pushButton_Home_Z, 0, 2, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_5, 3, 3, 1, 1)
        self.verticalLayout_13.addWidget(self.groupBox_XYZ)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_ConfigItem = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_ConfigItem.setObjectName("comboBox_ConfigItem")
        self.gridLayout_6.addWidget(self.comboBox_ConfigItem, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_ConfigInfo = QtWidgets.QLabel(self.tab_2)
        self.label_ConfigInfo.setObjectName("label_ConfigInfo")
        self.horizontalLayout_6.addWidget(self.label_ConfigInfo)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 0, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 3, 2, 1, 1)
        self.tableWidget_Config = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_Config.setObjectName("tableWidget_Config")
        self.tableWidget_Config.setColumnCount(0)
        self.tableWidget_Config.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidget_Config, 1, 1, 1, 3)
        self.pushButton_SetConfig = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_SetConfig.setIcon(icon17)
        self.pushButton_SetConfig.setObjectName("pushButton_SetConfig")
        self.gridLayout_6.addWidget(self.pushButton_SetConfig, 3, 3, 1, 1)
        self.lineEdit_ConfigValue = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_ConfigValue.setObjectName("lineEdit_ConfigValue")
        self.gridLayout_6.addWidget(self.lineEdit_ConfigValue, 0, 2, 1, 1)
        self.pushButton_RefreshConfig = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_RefreshConfig.setIcon(icon)
        self.pushButton_RefreshConfig.setObjectName("pushButton_RefreshConfig")
        self.gridLayout_6.addWidget(self.pushButton_RefreshConfig, 3, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_Gcode = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Gcode.sizePolicy().hasHeightForWidth())
        self.groupBox_Gcode.setSizePolicy(sizePolicy)
        self.groupBox_Gcode.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_Gcode.setObjectName("groupBox_Gcode")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_Gcode)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_Gcode = QtWidgets.QLineEdit(self.groupBox_Gcode)
        self.lineEdit_Gcode.setObjectName("lineEdit_Gcode")
        self.gridLayout_8.addWidget(self.lineEdit_Gcode, 0, 0, 1, 1)
        self.pushButton_Gcodesend = QtWidgets.QPushButton(self.groupBox_Gcode)
        self.pushButton_Gcodesend.setObjectName("pushButton_Gcodesend")
        self.gridLayout_8.addWidget(self.pushButton_Gcodesend, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_Gcode)
        self.groupBox_GcodeScript = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_GcodeScript.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox_GcodeScript.setObjectName("groupBox_GcodeScript")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_GcodeScript)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.plaintextEdit_GcodeScript_2 = QtWidgets.QPlainTextEdit(self.groupBox_GcodeScript)
        self.plaintextEdit_GcodeScript_2.setObjectName("plaintextEdit_GcodeScript_2")
        self.gridLayout_7.addWidget(self.plaintextEdit_GcodeScript_2, 0, 0, 1, 1)
        self.progressBar_Gcode = QtWidgets.QProgressBar(self.groupBox_GcodeScript)
        self.progressBar_Gcode.setProperty("value", 0)
        self.progressBar_Gcode.setObjectName("progressBar_Gcode")
        self.gridLayout_7.addWidget(self.progressBar_Gcode, 2, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_LoadGcode = QtWidgets.QPushButton(self.groupBox_GcodeScript)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_LoadGcode.sizePolicy().hasHeightForWidth())
        self.pushButton_LoadGcode.setSizePolicy(sizePolicy)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("img/open-file-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_LoadGcode.setIcon(icon23)
        self.pushButton_LoadGcode.setObjectName("pushButton_LoadGcode")
        self.verticalLayout_9.addWidget(self.pushButton_LoadGcode)
        self.pushButton_SaveGcode = QtWidgets.QPushButton(self.groupBox_GcodeScript)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SaveGcode.sizePolicy().hasHeightForWidth())
        self.pushButton_SaveGcode.setSizePolicy(sizePolicy)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("img/Floppy-Small-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_SaveGcode.setIcon(icon24)
        self.pushButton_SaveGcode.setObjectName("pushButton_SaveGcode")
        self.verticalLayout_9.addWidget(self.pushButton_SaveGcode)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.frame_GcodePauseStop = QtWidgets.QFrame(self.groupBox_GcodeScript)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_GcodePauseStop.sizePolicy().hasHeightForWidth())
        self.frame_GcodePauseStop.setSizePolicy(sizePolicy)
        self.frame_GcodePauseStop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_GcodePauseStop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_GcodePauseStop.setObjectName("frame_GcodePauseStop")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_GcodePauseStop)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_Hold_Start_Gcode = QtWidgets.QPushButton(self.frame_GcodePauseStop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Hold_Start_Gcode.sizePolicy().hasHeightForWidth())
        self.pushButton_Hold_Start_Gcode.setSizePolicy(sizePolicy)
        self.pushButton_Hold_Start_Gcode.setIcon(icon18)
        self.pushButton_Hold_Start_Gcode.setObjectName("pushButton_Hold_Start_Gcode")
        self.verticalLayout_8.addWidget(self.pushButton_Hold_Start_Gcode)
        self.pushButton_StopGcode = QtWidgets.QPushButton(self.frame_GcodePauseStop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_StopGcode.sizePolicy().hasHeightForWidth())
        self.pushButton_StopGcode.setSizePolicy(sizePolicy)
        self.pushButton_StopGcode.setIcon(icon19)
        self.pushButton_StopGcode.setObjectName("pushButton_StopGcode")
        self.verticalLayout_8.addWidget(self.pushButton_StopGcode)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_12.addWidget(self.frame_GcodePauseStop)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.checkBox_Gcode = QtWidgets.QCheckBox(self.groupBox_GcodeScript)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Gcode.sizePolicy().hasHeightForWidth())
        self.checkBox_Gcode.setSizePolicy(sizePolicy)
        self.checkBox_Gcode.setObjectName("checkBox_Gcode")
        self.verticalLayout_10.addWidget(self.checkBox_Gcode)
        self.comboBox_GcodeStreamType = QtWidgets.QComboBox(self.groupBox_GcodeScript)
        self.comboBox_GcodeStreamType.setObjectName("comboBox_GcodeStreamType")
        self.verticalLayout_10.addWidget(self.comboBox_GcodeStreamType)
        self.PushButton_RunGcodeScript = QtWidgets.QPushButton(self.groupBox_GcodeScript)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PushButton_RunGcodeScript.sizePolicy().hasHeightForWidth())
        self.PushButton_RunGcodeScript.setSizePolicy(sizePolicy)
        self.PushButton_RunGcodeScript.setObjectName("PushButton_RunGcodeScript")
        self.verticalLayout_10.addWidget(self.PushButton_RunGcodeScript)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.gridLayout_7.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.label_time = QtWidgets.QLabel(self.groupBox_GcodeScript)
        self.label_time.setObjectName("label_time")
        self.gridLayout_7.addWidget(self.label_time, 2, 1, 1, 1)
        self.progressBar_Gcodebuffer = QtWidgets.QProgressBar(self.groupBox_GcodeScript)
        self.progressBar_Gcodebuffer.setProperty("value", 0)
        self.progressBar_Gcodebuffer.setObjectName("progressBar_Gcodebuffer")
        self.gridLayout_7.addWidget(self.progressBar_Gcodebuffer, 1, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_7)
        self.verticalLayout_6.addWidget(self.groupBox_GcodeScript)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_4)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.groupBox_Image_Select = QtWidgets.QGroupBox(self.splitter_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_Image_Select.sizePolicy().hasHeightForWidth())
        self.groupBox_Image_Select.setSizePolicy(sizePolicy)
        self.groupBox_Image_Select.setMinimumSize(QtCore.QSize(250, 0))
        self.groupBox_Image_Select.setObjectName("groupBox_Image_Select")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_Image_Select)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.pushButton_Set_Changes_Image_Config = QtWidgets.QPushButton(self.groupBox_Image_Select)
        self.pushButton_Set_Changes_Image_Config.setObjectName("pushButton_Set_Changes_Image_Config")
        self.gridLayout_12.addWidget(self.pushButton_Set_Changes_Image_Config, 5, 0, 1, 1)
        self.pushButton_Process_Image = QtWidgets.QPushButton(self.groupBox_Image_Select)
        self.pushButton_Process_Image.setObjectName("pushButton_Process_Image")
        self.gridLayout_12.addWidget(self.pushButton_Process_Image, 0, 1, 1, 1)
        self.comboBox_Technique = QtWidgets.QComboBox(self.groupBox_Image_Select)
        self.comboBox_Technique.setObjectName("comboBox_Technique")
        self.gridLayout_12.addWidget(self.comboBox_Technique, 2, 1, 1, 1)
        self.label_Image_Process = QtWidgets.QLabel(self.groupBox_Image_Select)
        self.label_Image_Process.setObjectName("label_Image_Process")
        self.gridLayout_12.addWidget(self.label_Image_Process, 3, 0, 1, 1)
        self.label_Technique = QtWidgets.QLabel(self.groupBox_Image_Select)
        self.label_Technique.setObjectName("label_Technique")
        self.gridLayout_12.addWidget(self.label_Technique, 2, 0, 1, 1)
        self.label_Tool_Select = QtWidgets.QLabel(self.groupBox_Image_Select)
        self.label_Tool_Select.setObjectName("label_Tool_Select")
        self.gridLayout_12.addWidget(self.label_Tool_Select, 1, 0, 1, 1)
        self.pushButton_Save_Image_Config = QtWidgets.QPushButton(self.groupBox_Image_Select)
        self.pushButton_Save_Image_Config.setObjectName("pushButton_Save_Image_Config")
        self.gridLayout_12.addWidget(self.pushButton_Save_Image_Config, 6, 1, 1, 1)
        self.comboBox_Image_Process = QtWidgets.QComboBox(self.groupBox_Image_Select)
        self.comboBox_Image_Process.setObjectName("comboBox_Image_Process")
        self.gridLayout_12.addWidget(self.comboBox_Image_Process, 3, 1, 1, 1)
        self.tableWidget_Image_Config = QtWidgets.QTableWidget(self.groupBox_Image_Select)
        self.tableWidget_Image_Config.setObjectName("tableWidget_Image_Config")
        self.tableWidget_Image_Config.setColumnCount(0)
        self.tableWidget_Image_Config.setRowCount(0)
        self.gridLayout_12.addWidget(self.tableWidget_Image_Config, 4, 0, 1, 2)
        self.pushButton_Open_Image = QtWidgets.QPushButton(self.groupBox_Image_Select)
        self.pushButton_Open_Image.setObjectName("pushButton_Open_Image")
        self.gridLayout_12.addWidget(self.pushButton_Open_Image, 0, 0, 1, 1)
        self.pushButton_Load_Image_Config = QtWidgets.QPushButton(self.groupBox_Image_Select)
        self.pushButton_Load_Image_Config.setObjectName("pushButton_Load_Image_Config")
        self.gridLayout_12.addWidget(self.pushButton_Load_Image_Config, 5, 1, 1, 1)
        self.progressBar_Gimage = QtWidgets.QProgressBar(self.groupBox_Image_Select)
        self.progressBar_Gimage.setProperty("value", 0)
        self.progressBar_Gimage.setObjectName("progressBar_Gimage")
        self.gridLayout_12.addWidget(self.progressBar_Gimage, 7, 0, 1, 2)
        self.pushButton_Generate_Gimage_Code = QtWidgets.QPushButton(self.groupBox_Image_Select)
        self.pushButton_Generate_Gimage_Code.setObjectName("pushButton_Generate_Gimage_Code")
        self.gridLayout_12.addWidget(self.pushButton_Generate_Gimage_Code, 6, 0, 1, 1)
        self.comboBox_Tool_Select = QtWidgets.QComboBox(self.groupBox_Image_Select)
        self.comboBox_Tool_Select.setObjectName("comboBox_Tool_Select")
        self.gridLayout_12.addWidget(self.comboBox_Tool_Select, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.splitter_3)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_Image_Preview = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_Image_Preview.setObjectName("groupBox_Image_Preview")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_Image_Preview)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_Image_Preview = QtWidgets.QLabel(self.groupBox_Image_Preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image_Preview.sizePolicy().hasHeightForWidth())
        self.label_Image_Preview.setSizePolicy(sizePolicy)
        self.label_Image_Preview.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_Image_Preview.setText("")
        self.label_Image_Preview.setScaledContents(True)
        self.label_Image_Preview.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image_Preview.setObjectName("label_Image_Preview")
        self.gridLayout_10.addWidget(self.label_Image_Preview, 0, 0, 1, 1)
        self.groupBox_Image_Preview_Processed = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_Image_Preview_Processed.setObjectName("groupBox_Image_Preview_Processed")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_Image_Preview_Processed)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_Image_Preview_Processed = QtWidgets.QLabel(self.groupBox_Image_Preview_Processed)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Image_Preview_Processed.sizePolicy().hasHeightForWidth())
        self.label_Image_Preview_Processed.setSizePolicy(sizePolicy)
        self.label_Image_Preview_Processed.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_Image_Preview_Processed.setText("")
        self.label_Image_Preview_Processed.setScaledContents(True)
        self.label_Image_Preview_Processed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Image_Preview_Processed.setObjectName("label_Image_Preview_Processed")
        self.gridLayout_11.addWidget(self.label_Image_Preview_Processed, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.splitter_2)
        self.horizontalLayout_4.addWidget(self.splitter_3)
        self.tabWidget.addTab(self.tab_4, "")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_Logger = QtWidgets.QTextEdit(self.layoutWidget1)
        self.textEdit_Logger.setObjectName("textEdit_Logger")
        self.horizontalLayout.addWidget(self.textEdit_Logger)
        self.pushButton_Emergency = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_Emergency.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("img/Perspective-Button-Shutdown-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Emergency.setIcon(icon25)
        self.pushButton_Emergency.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_Emergency.setFlat(True)
        self.pushButton_Emergency.setObjectName("pushButton_Emergency")
        self.horizontalLayout.addWidget(self.pushButton_Emergency)
        self.verticalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuConfig = QtWidgets.QMenu(self.menuFile)
        self.menuConfig.setObjectName("menuConfig")
        self.menuGcode = QtWidgets.QMenu(self.menuFile)
        self.menuGcode.setObjectName("menuGcode")
        self.menuGimage = QtWidgets.QMenu(self.menuFile)
        self.menuGimage.setObjectName("menuGimage")
        self.menuInterface = QtWidgets.QMenu(self.menuFile)
        self.menuInterface.setObjectName("menuInterface")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_Config = QtWidgets.QAction(MainWindow)
        self.actionSave_Config.setObjectName("actionSave_Config")
        self.actionLoad_Gcode = QtWidgets.QAction(MainWindow)
        self.actionLoad_Gcode.setObjectName("actionLoad_Gcode")
        self.actionSave_Gcode = QtWidgets.QAction(MainWindow)
        self.actionSave_Gcode.setObjectName("actionSave_Gcode")
        self.actionSave_Gimage_Config = QtWidgets.QAction(MainWindow)
        self.actionSave_Gimage_Config.setObjectName("actionSave_Gimage_Config")
        self.actionLoad_Gimage_Config = QtWidgets.QAction(MainWindow)
        self.actionLoad_Gimage_Config.setObjectName("actionLoad_Gimage_Config")
        self.actionLoad_Image = QtWidgets.QAction(MainWindow)
        self.actionLoad_Image.setObjectName("actionLoad_Image")
        self.actionSave_Processed_Image = QtWidgets.QAction(MainWindow)
        self.actionSave_Processed_Image.setObjectName("actionSave_Processed_Image")
        self.actionSave_Gimage_Gcode = QtWidgets.QAction(MainWindow)
        self.actionSave_Gimage_Gcode.setObjectName("actionSave_Gimage_Gcode")
        self.actionLayer_Selection = QtWidgets.QAction(MainWindow)
        self.actionLayer_Selection.setObjectName("actionLayer_Selection")
        self.actionResize = QtWidgets.QAction(MainWindow)
        self.actionResize.setObjectName("actionResize")
        self.actionSave_svg_Gimage = QtWidgets.QAction(MainWindow)
        self.actionSave_svg_Gimage.setObjectName("actionSave_svg_Gimage")
        self.actionCommand_Configuration = QtWidgets.QAction(MainWindow)
        self.actionCommand_Configuration.setObjectName("actionCommand_Configuration")
        self.actionReload_Interface_Configuration = QtWidgets.QAction(MainWindow)
        self.actionReload_Interface_Configuration.setObjectName("actionReload_Interface_Configuration")
        self.menuConfig.addSeparator()
        self.menuConfig.addAction(self.actionSave_Config)
        self.menuGcode.addAction(self.actionLoad_Gcode)
        self.menuGcode.addAction(self.actionSave_Gcode)
        self.menuGimage.addAction(self.actionSave_Gimage_Config)
        self.menuGimage.addAction(self.actionLoad_Gimage_Config)
        self.menuGimage.addSeparator()
        self.menuGimage.addAction(self.actionLoad_Image)
        self.menuGimage.addAction(self.actionSave_Processed_Image)
        self.menuGimage.addSeparator()
        self.menuGimage.addAction(self.actionSave_Gimage_Gcode)
        self.menuGimage.addSeparator()
        self.menuGimage.addAction(self.actionSave_svg_Gimage)
        self.menuInterface.addAction(self.actionReload_Interface_Configuration)
        self.menuFile.addAction(self.menuConfig.menuAction())
        self.menuFile.addAction(self.menuGcode.menuAction())
        self.menuFile.addAction(self.menuGimage.menuAction())
        self.menuFile.addAction(self.menuInterface.menuAction())
        self.menuTools.addAction(self.actionLayer_Selection)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionResize)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionCommand_Configuration)
        self.menuTools.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "XYZ Mover by FG"))
        self.groupBoxConnect.setTitle(_translate("MainWindow", "Connect"))
        self.label_COM.setText(_translate("MainWindow", "COM Port"))
        self.label_ConnSpeed.setText(_translate("MainWindow", "Connection Speed"))
        self.pushButton_Refresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButton_Connect.setText(_translate("MainWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Connect"))
        self.groupBox_XYZ.setTitle(_translate("MainWindow", "XYZ Mover"))
        self.label_XY.setText(_translate("MainWindow", "XY"))
        self.label_Z.setText(_translate("MainWindow", "Z"))
        self.label_YZ.setText(_translate("MainWindow", "  YZ"))
        self.label_XZ.setText(_translate("MainWindow", "  XZ"))
        self.groupBox_actPosition.setTitle(_translate("MainWindow", "Actual Position"))
        self.label_XactPos.setText(_translate("MainWindow", "X=  NA"))
        self.label_YactPos.setText(_translate("MainWindow", "Y=  NA"))
        self.label_ZactPos.setText(_translate("MainWindow", "Z=  NA"))
        self.pushButton_SetPos.setToolTip(_translate("MainWindow", "setPosition action using XYZ fields"))
        self.pushButton_SetPos.setText(_translate("MainWindow", "Set"))
        self.label_Stateact.setText(_translate("MainWindow", "S_XYZ=NA"))
        self.groupBox_DeltaMove.setTitle(_translate("MainWindow", "Delta"))
        self.label_DeltaX.setText(_translate("MainWindow", "X"))
        self.label_DeltaY.setText(_translate("MainWindow", "Y"))
        self.label_DeltaZ.setText(_translate("MainWindow", "Z"))
        self.label_Xpos.setText(_translate("MainWindow", "X"))
        self.label_Ypos.setText(_translate("MainWindow", "Y"))
        self.label_Zpos.setText(_translate("MainWindow", "Z "))
        self.label_Feedrate.setText(_translate("MainWindow", "F"))
        self.pushButton_Go.setToolTip(_translate("MainWindow", "rapidMove using XYZ or linearMove using XYZF Fields"))
        self.pushButton_Go.setText(_translate("MainWindow", "GO"))
        self.pushButton_Pause_Resume.setToolTip(_translate("MainWindow", "quickPause or quickResume action"))
        self.pushButton_Pause_Resume.setText(_translate("MainWindow", "Hold"))
        self.pushButton_MoveStop.setToolTip(_translate("MainWindow", "quickStop action"))
        self.pushButton_MoveStop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_CleanAlarm.setToolTip(_translate("MainWindow", "clearAlarm action"))
        self.pushButton_CleanAlarm.setText(_translate("MainWindow", "Clear Alarm"))
        self.pushButton_Home.setToolTip(_translate("MainWindow", "userHome action"))
        self.pushButton_Home.setText(_translate("MainWindow", "Home"))
        self.pushButton_Reset.setToolTip(_translate("MainWindow", "softReset action"))
        self.pushButton_Reset.setText(_translate("MainWindow", "Reset Signal"))
        self.pushButton_Home_X.setToolTip(_translate("MainWindow", "HomeX action"))
        self.pushButton_Home_X.setText(_translate("MainWindow", "X"))
        self.pushButton_Home_Y.setToolTip(_translate("MainWindow", "HomeY action"))
        self.pushButton_Home_Y.setText(_translate("MainWindow", "Y"))
        self.pushButton_Home_Z.setToolTip(_translate("MainWindow", "HomeZ action"))
        self.pushButton_Home_Z.setText(_translate("MainWindow", "Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Move"))
        self.label_ConfigInfo.setText(_translate("MainWindow", "NA"))
        self.pushButton_SetConfig.setText(_translate("MainWindow", "Set Value"))
        self.pushButton_RefreshConfig.setText(_translate("MainWindow", "Refresh Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Config"))
        self.groupBox_Gcode.setTitle(_translate("MainWindow", "Gcode input"))
        self.pushButton_Gcodesend.setText(_translate("MainWindow", "Gcode Send"))
        self.groupBox_GcodeScript.setTitle(_translate("MainWindow", "Gcode Script"))
        self.pushButton_LoadGcode.setText(_translate("MainWindow", "Load Gcode"))
        self.pushButton_SaveGcode.setText(_translate("MainWindow", "Save Gcode"))
        self.pushButton_Hold_Start_Gcode.setText(_translate("MainWindow", "Hold"))
        self.pushButton_StopGcode.setText(_translate("MainWindow", "STOP"))
        self.checkBox_Gcode.setText(_translate("MainWindow", "Check Gcode"))
        self.PushButton_RunGcodeScript.setText(_translate("MainWindow", "Run Gcode"))
        self.label_time.setText(_translate("MainWindow", "00:00:00"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Gcode"))
        self.groupBox_Image_Select.setTitle(_translate("MainWindow", "Image Select"))
        self.pushButton_Set_Changes_Image_Config.setText(_translate("MainWindow", "Set Changes"))
        self.pushButton_Process_Image.setText(_translate("MainWindow", "Apply Process"))
        self.label_Image_Process.setText(_translate("MainWindow", "Image Process"))
        self.label_Technique.setText(_translate("MainWindow", "Technique"))
        self.label_Tool_Select.setText(_translate("MainWindow", "Tool"))
        self.pushButton_Save_Image_Config.setText(_translate("MainWindow", "Save Image Config"))
        self.pushButton_Open_Image.setText(_translate("MainWindow", "Open Image"))
        self.pushButton_Load_Image_Config.setText(_translate("MainWindow", "Load Image Config"))
        self.pushButton_Generate_Gimage_Code.setText(_translate("MainWindow", "Generate Gimage Code"))
        self.groupBox_Image_Preview.setTitle(_translate("MainWindow", "Image Preview"))
        self.label_Image_Preview.setToolTip(_translate("MainWindow", "Double Click to Open Image"))
        self.groupBox_Image_Preview_Processed.setTitle(_translate("MainWindow", "Processed Image Preview"))
        self.label_Image_Preview_Processed.setToolTip(_translate("MainWindow", "Double Click to Open Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Gimage"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuConfig.setTitle(_translate("MainWindow", "Config"))
        self.menuGcode.setTitle(_translate("MainWindow", "Gcode"))
        self.menuGimage.setTitle(_translate("MainWindow", "Gimage"))
        self.menuInterface.setTitle(_translate("MainWindow", "Interface"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave_Config.setText(_translate("MainWindow", "Save Config"))
        self.actionLoad_Gcode.setText(_translate("MainWindow", "Load Gcode"))
        self.actionSave_Gcode.setText(_translate("MainWindow", "Save Gcode "))
        self.actionSave_Gimage_Config.setText(_translate("MainWindow", "Save Gimage Config"))
        self.actionLoad_Gimage_Config.setText(_translate("MainWindow", "Load Gimage Config"))
        self.actionLoad_Image.setText(_translate("MainWindow", "Load Image"))
        self.actionSave_Processed_Image.setText(_translate("MainWindow", "Save Processed Image"))
        self.actionSave_Gimage_Gcode.setText(_translate("MainWindow", "Save Gimage Gcode"))
        self.actionLayer_Selection.setText(_translate("MainWindow", "GImage Layer Selection"))
        self.actionResize.setText(_translate("MainWindow", "GImage Resize and Positioning"))
        self.actionSave_svg_Gimage.setText(_translate("MainWindow", "Save svg Gimage"))
        self.actionCommand_Configuration.setText(_translate("MainWindow", "Interface Configuration"))
        self.actionReload_Interface_Configuration.setText(_translate("MainWindow", "Reload Interface Configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
