# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GuiXYZ_CommandConfigurationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_CCD(object):
    def setupUi(self, Dialog_CCD):
        Dialog_CCD.setObjectName("Dialog_CCD")
        Dialog_CCD.resize(675, 570)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_CCD)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_CCD = QtWidgets.QGroupBox(Dialog_CCD)
        self.groupBox_CCD.setObjectName("groupBox_CCD")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_CCD)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.groupBox_CCD)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget_CCD = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget_CCD.setObjectName("tableWidget_CCD")
        self.tableWidget_CCD.setColumnCount(0)
        self.tableWidget_CCD.setRowCount(0)
        self.frame_CCD = QtWidgets.QFrame(self.splitter)
        self.frame_CCD.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_CCD.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_CCD.setObjectName("frame_CCD")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_CCD)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_CCD_interface = QtWidgets.QComboBox(self.frame_CCD)
        self.comboBox_CCD_interface.setObjectName("comboBox_CCD_interface")
        self.horizontalLayout.addWidget(self.comboBox_CCD_interface)
        self.label_CCD_interfaceName = QtWidgets.QLabel(self.frame_CCD)
        self.label_CCD_interfaceName.setText("")
        self.label_CCD_interfaceName.setObjectName("label_CCD_interfaceName")
        self.horizontalLayout.addWidget(self.label_CCD_interfaceName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget_CCD_configs = QtWidgets.QTabWidget(self.frame_CCD)
        self.tabWidget_CCD_configs.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_CCD_configs.setObjectName("tabWidget_CCD_configs")
        self.tab_CCD_ActionConfig = QtWidgets.QWidget()
        self.tab_CCD_ActionConfig.setObjectName("tab_CCD_ActionConfig")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_CCD_ActionConfig)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_CCD_actionFiles = QtWidgets.QGroupBox(self.tab_CCD_ActionConfig)
        self.groupBox_CCD_actionFiles.setObjectName("groupBox_CCD_actionFiles")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_CCD_actionFiles)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_CCD_Command_Filename = QtWidgets.QLabel(self.groupBox_CCD_actionFiles)
        self.label_CCD_Command_Filename.setObjectName("label_CCD_Command_Filename")
        self.gridLayout_2.addWidget(self.label_CCD_Command_Filename, 0, 1, 1, 1)
        self.pushButton_CCD_Load_Commands = QtWidgets.QPushButton(self.groupBox_CCD_actionFiles)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/open-file-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_CCD_Load_Commands.setIcon(icon)
        self.pushButton_CCD_Load_Commands.setObjectName("pushButton_CCD_Load_Commands")
        self.gridLayout_2.addWidget(self.pushButton_CCD_Load_Commands, 1, 0, 1, 1)
        self.pushButton_CCD_Save_Commands = QtWidgets.QPushButton(self.groupBox_CCD_actionFiles)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/Save-as-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_CCD_Save_Commands.setIcon(icon1)
        self.pushButton_CCD_Save_Commands.setObjectName("pushButton_CCD_Save_Commands")
        self.gridLayout_2.addWidget(self.pushButton_CCD_Save_Commands, 1, 1, 1, 1)
        self.pushButton_CCD_Select_File = QtWidgets.QPushButton(self.groupBox_CCD_actionFiles)
        self.pushButton_CCD_Select_File.setObjectName("pushButton_CCD_Select_File")
        self.gridLayout_2.addWidget(self.pushButton_CCD_Select_File, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_CCD_actionFiles, 0, 0, 1, 1)
        self.groupBox_CCD_actionChanges = QtWidgets.QGroupBox(self.tab_CCD_ActionConfig)
        self.groupBox_CCD_actionChanges.setObjectName("groupBox_CCD_actionChanges")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_CCD_actionChanges)
        self.formLayout.setObjectName("formLayout")
        self.tableWidget_CCD_actionParam = QtWidgets.QTableWidget(self.groupBox_CCD_actionChanges)
        self.tableWidget_CCD_actionParam.setObjectName("tableWidget_CCD_actionParam")
        self.tableWidget_CCD_actionParam.setColumnCount(0)
        self.tableWidget_CCD_actionParam.setRowCount(0)
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.tableWidget_CCD_actionParam)
        self.comboBox_CCD_action = QtWidgets.QComboBox(self.groupBox_CCD_actionChanges)
        self.comboBox_CCD_action.setObjectName("comboBox_CCD_action")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.comboBox_CCD_action)
        self.lineEdit_CCD_Format = QtWidgets.QLineEdit(self.groupBox_CCD_actionChanges)
        self.lineEdit_CCD_Format.setObjectName("lineEdit_CCD_Format")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_CCD_Format)
        self.pushButton_CCD_actionTest = QtWidgets.QPushButton(self.groupBox_CCD_actionChanges)
        self.pushButton_CCD_actionTest.setObjectName("pushButton_CCD_actionTest")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton_CCD_actionTest)
        self.label_CCD_testResultFormat = QtWidgets.QLabel(self.groupBox_CCD_actionChanges)
        self.label_CCD_testResultFormat.setText("")
        self.label_CCD_testResultFormat.setObjectName("label_CCD_testResultFormat")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_CCD_testResultFormat)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_CCD_action = QtWidgets.QLineEdit(self.groupBox_CCD_actionChanges)
        self.lineEdit_CCD_action.setObjectName("lineEdit_CCD_action")
        self.horizontalLayout_2.addWidget(self.lineEdit_CCD_action)
        self.pushButton_CCD_actionAdd = QtWidgets.QPushButton(self.groupBox_CCD_actionChanges)
        self.pushButton_CCD_actionAdd.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_CCD_actionAdd.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_CCD_actionAdd.setIcon(icon2)
        self.pushButton_CCD_actionAdd.setObjectName("pushButton_CCD_actionAdd")
        self.horizontalLayout_2.addWidget(self.pushButton_CCD_actionAdd)
        self.pushButton_CCD_actionDel = QtWidgets.QPushButton(self.groupBox_CCD_actionChanges)
        self.pushButton_CCD_actionDel.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_CCD_actionDel.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/math-minus-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_CCD_actionDel.setIcon(icon3)
        self.pushButton_CCD_actionDel.setObjectName("pushButton_CCD_actionDel")
        self.horizontalLayout_2.addWidget(self.pushButton_CCD_actionDel)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.label_CCD_testResult = QtWidgets.QLabel(self.groupBox_CCD_actionChanges)
        self.label_CCD_testResult.setText("")
        self.label_CCD_testResult.setObjectName("label_CCD_testResult")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_CCD_testResult)
        self.gridLayout_3.addWidget(self.groupBox_CCD_actionChanges, 1, 0, 1, 1)
        self.tabWidget_CCD_configs.addTab(self.tab_CCD_ActionConfig, "")
        self.tab_CCD_ReadConfig = QtWidgets.QWidget()
        self.tab_CCD_ReadConfig.setObjectName("tab_CCD_ReadConfig")
        self.tabWidget_CCD_configs.addTab(self.tab_CCD_ReadConfig, "")
        self.tab_CCD_GeneralConfig = QtWidgets.QWidget()
        self.tab_CCD_GeneralConfig.setObjectName("tab_CCD_GeneralConfig")
        self.tabWidget_CCD_configs.addTab(self.tab_CCD_GeneralConfig, "")
        self.verticalLayout_2.addWidget(self.tabWidget_CCD_configs)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_CCD)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_CCD)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_CCD)
        self.tabWidget_CCD_configs.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog_CCD.accept)
        self.buttonBox.rejected.connect(Dialog_CCD.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_CCD)

    def retranslateUi(self, Dialog_CCD):
        _translate = QtCore.QCoreApplication.translate
        Dialog_CCD.setWindowTitle(_translate("Dialog_CCD", "Command Configuration Dialog"))
        self.groupBox_CCD.setTitle(_translate("Dialog_CCD", "Command Configuration"))
        self.groupBox_CCD_actionFiles.setTitle(_translate("Dialog_CCD", "Filename"))
        self.label_CCD_Command_Filename.setText(_translate("Dialog_CCD", "Filename"))
        self.pushButton_CCD_Load_Commands.setText(_translate("Dialog_CCD", "Load Commands"))
        self.pushButton_CCD_Save_Commands.setText(_translate("Dialog_CCD", "Save Commands"))
        self.pushButton_CCD_Select_File.setText(_translate("Dialog_CCD", "Select File"))
        self.groupBox_CCD_actionChanges.setTitle(_translate("Dialog_CCD", "Actions"))
        self.tableWidget_CCD_actionParam.setToolTip(_translate("Dialog_CCD", "Parameters of Format"))
        self.lineEdit_CCD_Format.setToolTip(_translate("Dialog_CCD", "Format Field"))
        self.pushButton_CCD_actionTest.setText(_translate("Dialog_CCD", "Test Action"))
        self.label_CCD_testResultFormat.setToolTip(_translate("Dialog_CCD", "Format interpretation"))
        self.lineEdit_CCD_action.setToolTip(_translate("Dialog_CCD", "action Name Field"))
        self.pushButton_CCD_actionAdd.setToolTip(_translate("Dialog_CCD", "Add new action or Replace format in action"))
        self.pushButton_CCD_actionDel.setToolTip(_translate("Dialog_CCD", "Delete action or clear format in action"))
        self.label_CCD_testResult.setToolTip(_translate("Dialog_CCD", "Gcode interpretation Result"))
        self.tabWidget_CCD_configs.setTabText(self.tabWidget_CCD_configs.indexOf(self.tab_CCD_ActionConfig), _translate("Dialog_CCD", "Action Config"))
        self.tabWidget_CCD_configs.setTabText(self.tabWidget_CCD_configs.indexOf(self.tab_CCD_ReadConfig), _translate("Dialog_CCD", "Read Config"))
        self.tabWidget_CCD_configs.setTabText(self.tabWidget_CCD_configs.indexOf(self.tab_CCD_GeneralConfig), _translate("Dialog_CCD", "General Config"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_CCD = QtWidgets.QDialog()
    ui = Ui_Dialog_CCD()
    ui.setupUi(Dialog_CCD)
    Dialog_CCD.show()
    sys.exit(app.exec_())
