# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GuiXYZ_VariableButtonDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_VBDD(object):
    def setupUi(self, Dialog_VBDD):
        Dialog_VBDD.setObjectName("Dialog_VBDD")
        Dialog_VBDD.resize(508, 586)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_VBDD)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_VBDF = QtWidgets.QTabWidget(Dialog_VBDD)
        self.tabWidget_VBDF.setObjectName("tabWidget_VBDF")
        self.tabWidget_VBDF_General = QtWidgets.QWidget()
        self.tabWidget_VBDF_General.setObjectName("tabWidget_VBDF_General")
        self.gridLayout = QtWidgets.QGridLayout(self.tabWidget_VBDF_General)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_VBDD_General = QtWidgets.QGroupBox(self.tabWidget_VBDF_General)
        self.groupBox_VBDD_General.setObjectName("groupBox_VBDD_General")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_General)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_VBDD_Name = QtWidgets.QLabel(self.groupBox_VBDD_General)
        self.label_VBDD_Name.setObjectName("label_VBDD_Name")
        self.horizontalLayout.addWidget(self.label_VBDD_Name)
        self.lineEdit_VBDD_Name = QtWidgets.QLineEdit(self.groupBox_VBDD_General)
        self.lineEdit_VBDD_Name.setObjectName("lineEdit_VBDD_Name")
        self.horizontalLayout.addWidget(self.lineEdit_VBDD_Name)
        self.verticalLayout_15.addLayout(self.horizontalLayout)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_VBDD_kind = QtWidgets.QLabel(self.groupBox_VBDD_General)
        self.label_VBDD_kind.setObjectName("label_VBDD_kind")
        self.horizontalLayout_13.addWidget(self.label_VBDD_kind)
        self.comboBox_VBDD_batton_kind = QtWidgets.QComboBox(self.groupBox_VBDD_General)
        self.comboBox_VBDD_batton_kind.setObjectName("comboBox_VBDD_batton_kind")
        self.horizontalLayout_13.addWidget(self.comboBox_VBDD_batton_kind)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.gridLayout.addWidget(self.groupBox_VBDD_General, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.groupBox_VBDD_Position_Size = QtWidgets.QGroupBox(self.tabWidget_VBDF_General)
        self.groupBox_VBDD_Position_Size.setCheckable(True)
        self.groupBox_VBDD_Position_Size.setChecked(False)
        self.groupBox_VBDD_Position_Size.setObjectName("groupBox_VBDD_Position_Size")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_Position_Size)
        self.verticalLayout_18.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_VBDD_Position = QtWidgets.QLabel(self.groupBox_VBDD_Position_Size)
        self.label_VBDD_Position.setObjectName("label_VBDD_Position")
        self.horizontalLayout_19.addWidget(self.label_VBDD_Position)
        self.lineEdit_VBDD_Position_X = QtWidgets.QLineEdit(self.groupBox_VBDD_Position_Size)
        self.lineEdit_VBDD_Position_X.setObjectName("lineEdit_VBDD_Position_X")
        self.horizontalLayout_19.addWidget(self.lineEdit_VBDD_Position_X)
        self.lineEdit_VBDD_Position_Y = QtWidgets.QLineEdit(self.groupBox_VBDD_Position_Size)
        self.lineEdit_VBDD_Position_Y.setObjectName("lineEdit_VBDD_Position_Y")
        self.horizontalLayout_19.addWidget(self.lineEdit_VBDD_Position_Y)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.verticalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_VBDD_Size = QtWidgets.QLabel(self.groupBox_VBDD_Position_Size)
        self.label_VBDD_Size.setObjectName("label_VBDD_Size")
        self.horizontalLayout_20.addWidget(self.label_VBDD_Size)
        self.lineEdit_VBDD_Size_X = QtWidgets.QLineEdit(self.groupBox_VBDD_Position_Size)
        self.lineEdit_VBDD_Size_X.setObjectName("lineEdit_VBDD_Size_X")
        self.horizontalLayout_20.addWidget(self.lineEdit_VBDD_Size_X)
        self.lineEdit_VBDD_Size_Y = QtWidgets.QLineEdit(self.groupBox_VBDD_Position_Size)
        self.lineEdit_VBDD_Size_Y.setObjectName("lineEdit_VBDD_Size_Y")
        self.horizontalLayout_20.addWidget(self.lineEdit_VBDD_Size_Y)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_VBDD_MarginSize = QtWidgets.QLabel(self.groupBox_VBDD_Position_Size)
        self.label_VBDD_MarginSize.setObjectName("label_VBDD_MarginSize")
        self.horizontalLayout_21.addWidget(self.label_VBDD_MarginSize)
        self.lineEdit_VBDD_MarginSize = QtWidgets.QLineEdit(self.groupBox_VBDD_Position_Size)
        self.lineEdit_VBDD_MarginSize.setObjectName("lineEdit_VBDD_MarginSize")
        self.horizontalLayout_21.addWidget(self.lineEdit_VBDD_MarginSize)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem4)
        self.verticalLayout_18.addLayout(self.horizontalLayout_21)
        self.gridLayout.addWidget(self.groupBox_VBDD_Position_Size, 2, 0, 1, 1)
        self.tabWidget_VBDF.addTab(self.tabWidget_VBDF_General, "")
        self.tabWidget_VBDF_First_State = QtWidgets.QWidget()
        self.tabWidget_VBDF_First_State.setObjectName("tabWidget_VBDF_First_State")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabWidget_VBDF_First_State)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_VBDD_id = QtWidgets.QLabel(self.tabWidget_VBDF_First_State)
        self.label_VBDD_id.setObjectName("label_VBDD_id")
        self.horizontalLayout_4.addWidget(self.label_VBDD_id)
        self.pushButton_VBDD_Icon = QtWidgets.QPushButton(self.tabWidget_VBDF_First_State)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/Actions-arrow-up-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBDD_Icon.setIcon(icon)
        self.pushButton_VBDD_Icon.setObjectName("pushButton_VBDD_Icon")
        self.horizontalLayout_4.addWidget(self.pushButton_VBDD_Icon)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_VBDD_batton_type = QtWidgets.QLabel(self.tabWidget_VBDF_First_State)
        self.label_VBDD_batton_type.setObjectName("label_VBDD_batton_type")
        self.horizontalLayout_7.addWidget(self.label_VBDD_batton_type)
        self.comboBox_VBDD_batton_type = QtWidgets.QComboBox(self.tabWidget_VBDF_First_State)
        self.comboBox_VBDD_batton_type.setObjectName("comboBox_VBDD_batton_type")
        self.horizontalLayout_7.addWidget(self.comboBox_VBDD_batton_type)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.groupBox_VBDD_byaction = QtWidgets.QGroupBox(self.tabWidget_VBDF_First_State)
        self.groupBox_VBDD_byaction.setCheckable(True)
        self.groupBox_VBDD_byaction.setObjectName("groupBox_VBDD_byaction")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_VBDD_byaction)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_VBDD_CHid = QtWidgets.QLabel(self.groupBox_VBDD_byaction)
        self.label_VBDD_CHid.setObjectName("label_VBDD_CHid")
        self.horizontalLayout_3.addWidget(self.label_VBDD_CHid)
        self.label_VBDD_Force_id = QtWidgets.QLabel(self.groupBox_VBDD_byaction)
        self.label_VBDD_Force_id.setObjectName("label_VBDD_Force_id")
        self.horizontalLayout_3.addWidget(self.label_VBDD_Force_id)
        self.comboBox_VBDD_CHid = QtWidgets.QComboBox(self.groupBox_VBDD_byaction)
        self.comboBox_VBDD_CHid.setObjectName("comboBox_VBDD_CHid")
        self.horizontalLayout_3.addWidget(self.comboBox_VBDD_CHid)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_VBDD_action = QtWidgets.QLabel(self.groupBox_VBDD_byaction)
        self.label_VBDD_action.setObjectName("label_VBDD_action")
        self.horizontalLayout_2.addWidget(self.label_VBDD_action)
        self.comboBox_VBDD_action = QtWidgets.QComboBox(self.groupBox_VBDD_byaction)
        self.comboBox_VBDD_action.setObjectName("comboBox_VBDD_action")
        self.horizontalLayout_2.addWidget(self.comboBox_VBDD_action)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.groupBox_VBDD_Parameters = QtWidgets.QGroupBox(self.groupBox_VBDD_byaction)
        self.groupBox_VBDD_Parameters.setCheckable(True)
        self.groupBox_VBDD_Parameters.setObjectName("groupBox_VBDD_Parameters")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_Parameters)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tableWidget_VBDD_parameters = QtWidgets.QTableWidget(self.groupBox_VBDD_Parameters)
        self.tableWidget_VBDD_parameters.setObjectName("tableWidget_VBDD_parameters")
        self.tableWidget_VBDD_parameters.setColumnCount(0)
        self.tableWidget_VBDD_parameters.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_VBDD_parameters)
        self.gridLayout_2.addWidget(self.groupBox_VBDD_Parameters, 4, 0, 2, 1)
        self.verticalLayout_6.addWidget(self.groupBox_VBDD_byaction)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_VBDD_Format = QtWidgets.QLabel(self.tabWidget_VBDF_First_State)
        self.label_VBDD_Format.setObjectName("label_VBDD_Format")
        self.verticalLayout_2.addWidget(self.label_VBDD_Format)
        self.label_VBDD_Result = QtWidgets.QLabel(self.tabWidget_VBDF_First_State)
        self.label_VBDD_Result.setObjectName("label_VBDD_Result")
        self.verticalLayout_2.addWidget(self.label_VBDD_Result)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.groupBox_VBDD_byGcode = QtWidgets.QGroupBox(self.tabWidget_VBDF_First_State)
        self.groupBox_VBDD_byGcode.setCheckable(True)
        self.groupBox_VBDD_byGcode.setChecked(False)
        self.groupBox_VBDD_byGcode.setObjectName("groupBox_VBDD_byGcode")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_byGcode)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit_VBDD_Gcode = QtWidgets.QPlainTextEdit(self.groupBox_VBDD_byGcode)
        self.plainTextEdit_VBDD_Gcode.setObjectName("plainTextEdit_VBDD_Gcode")
        self.verticalLayout_3.addWidget(self.plainTextEdit_VBDD_Gcode)
        self.verticalLayout_6.addWidget(self.groupBox_VBDD_byGcode)
        self.groupBox_VBDD_byScript = QtWidgets.QGroupBox(self.tabWidget_VBDF_First_State)
        self.groupBox_VBDD_byScript.setCheckable(True)
        self.groupBox_VBDD_byScript.setChecked(False)
        self.groupBox_VBDD_byScript.setObjectName("groupBox_VBDD_byScript")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_VBDD_byScript)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_VBDD_Script = QtWidgets.QLabel(self.groupBox_VBDD_byScript)
        self.label_VBDD_Script.setObjectName("label_VBDD_Script")
        self.horizontalLayout_5.addWidget(self.label_VBDD_Script)
        self.pushButton_VBDD_Script = QtWidgets.QPushButton(self.groupBox_VBDD_byScript)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/Document-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBDD_Script.setIcon(icon1)
        self.pushButton_VBDD_Script.setObjectName("pushButton_VBDD_Script")
        self.horizontalLayout_5.addWidget(self.pushButton_VBDD_Script)
        self.verticalLayout_6.addWidget(self.groupBox_VBDD_byScript)
        self.tabWidget_VBDF.addTab(self.tabWidget_VBDF_First_State, "")
        self.tabWidget_VBDF_Second_State = QtWidgets.QWidget()
        self.tabWidget_VBDF_Second_State.setObjectName("tabWidget_VBDF_Second_State")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabWidget_VBDF_Second_State)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_VBDD_id_2 = QtWidgets.QLabel(self.tabWidget_VBDF_Second_State)
        self.label_VBDD_id_2.setObjectName("label_VBDD_id_2")
        self.horizontalLayout_8.addWidget(self.label_VBDD_id_2)
        self.pushButton_VBDD_Icon_2 = QtWidgets.QPushButton(self.tabWidget_VBDF_Second_State)
        self.pushButton_VBDD_Icon_2.setIcon(icon)
        self.pushButton_VBDD_Icon_2.setObjectName("pushButton_VBDD_Icon_2")
        self.horizontalLayout_8.addWidget(self.pushButton_VBDD_Icon_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_VBDD_batton_type_2 = QtWidgets.QLabel(self.tabWidget_VBDF_Second_State)
        self.label_VBDD_batton_type_2.setObjectName("label_VBDD_batton_type_2")
        self.horizontalLayout_11.addWidget(self.label_VBDD_batton_type_2)
        self.comboBox_VBDD_batton_type_2 = QtWidgets.QComboBox(self.tabWidget_VBDF_Second_State)
        self.comboBox_VBDD_batton_type_2.setObjectName("comboBox_VBDD_batton_type_2")
        self.horizontalLayout_11.addWidget(self.comboBox_VBDD_batton_type_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.groupBox_VBDD_byaction_2 = QtWidgets.QGroupBox(self.tabWidget_VBDF_Second_State)
        self.groupBox_VBDD_byaction_2.setCheckable(True)
        self.groupBox_VBDD_byaction_2.setObjectName("groupBox_VBDD_byaction_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_VBDD_byaction_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_VBDD_CHid_2 = QtWidgets.QLabel(self.groupBox_VBDD_byaction_2)
        self.label_VBDD_CHid_2.setObjectName("label_VBDD_CHid_2")
        self.horizontalLayout_9.addWidget(self.label_VBDD_CHid_2)
        self.label_VBDD_Force_id_2 = QtWidgets.QLabel(self.groupBox_VBDD_byaction_2)
        self.label_VBDD_Force_id_2.setObjectName("label_VBDD_Force_id_2")
        self.horizontalLayout_9.addWidget(self.label_VBDD_Force_id_2)
        self.comboBox_VBDD_CHid_2 = QtWidgets.QComboBox(self.groupBox_VBDD_byaction_2)
        self.comboBox_VBDD_CHid_2.setObjectName("comboBox_VBDD_CHid_2")
        self.horizontalLayout_9.addWidget(self.comboBox_VBDD_CHid_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_VBDD_action_2 = QtWidgets.QLabel(self.groupBox_VBDD_byaction_2)
        self.label_VBDD_action_2.setObjectName("label_VBDD_action_2")
        self.horizontalLayout_10.addWidget(self.label_VBDD_action_2)
        self.comboBox_VBDD_action_2 = QtWidgets.QComboBox(self.groupBox_VBDD_byaction_2)
        self.comboBox_VBDD_action_2.setObjectName("comboBox_VBDD_action_2")
        self.horizontalLayout_10.addWidget(self.comboBox_VBDD_action_2)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 3, 0, 1, 1)
        self.groupBox_VBDD_Parameters_2 = QtWidgets.QGroupBox(self.groupBox_VBDD_byaction_2)
        self.groupBox_VBDD_Parameters_2.setCheckable(True)
        self.groupBox_VBDD_Parameters_2.setObjectName("groupBox_VBDD_Parameters_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_Parameters_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_VBDD_parameters_2 = QtWidgets.QTableWidget(self.groupBox_VBDD_Parameters_2)
        self.tableWidget_VBDD_parameters_2.setObjectName("tableWidget_VBDD_parameters_2")
        self.tableWidget_VBDD_parameters_2.setColumnCount(0)
        self.tableWidget_VBDD_parameters_2.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_VBDD_parameters_2)
        self.gridLayout_3.addWidget(self.groupBox_VBDD_Parameters_2, 4, 0, 2, 1)
        self.verticalLayout_9.addWidget(self.groupBox_VBDD_byaction_2)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_VBDD_Format_2 = QtWidgets.QLabel(self.tabWidget_VBDF_Second_State)
        self.label_VBDD_Format_2.setObjectName("label_VBDD_Format_2")
        self.verticalLayout_7.addWidget(self.label_VBDD_Format_2)
        self.label_VBDD_Result_2 = QtWidgets.QLabel(self.tabWidget_VBDF_Second_State)
        self.label_VBDD_Result_2.setObjectName("label_VBDD_Result_2")
        self.verticalLayout_7.addWidget(self.label_VBDD_Result_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        self.groupBox_VBDD_byGcode_2 = QtWidgets.QGroupBox(self.tabWidget_VBDF_Second_State)
        self.groupBox_VBDD_byGcode_2.setCheckable(True)
        self.groupBox_VBDD_byGcode_2.setChecked(False)
        self.groupBox_VBDD_byGcode_2.setObjectName("groupBox_VBDD_byGcode_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_byGcode_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.plainTextEdit_VBDD_Gcode_2 = QtWidgets.QPlainTextEdit(self.groupBox_VBDD_byGcode_2)
        self.plainTextEdit_VBDD_Gcode_2.setObjectName("plainTextEdit_VBDD_Gcode_2")
        self.verticalLayout_8.addWidget(self.plainTextEdit_VBDD_Gcode_2)
        self.verticalLayout_9.addWidget(self.groupBox_VBDD_byGcode_2)
        self.groupBox_VBDD_byScript_2 = QtWidgets.QGroupBox(self.tabWidget_VBDF_Second_State)
        self.groupBox_VBDD_byScript_2.setCheckable(True)
        self.groupBox_VBDD_byScript_2.setChecked(False)
        self.groupBox_VBDD_byScript_2.setObjectName("groupBox_VBDD_byScript_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_VBDD_byScript_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_VBDD_Script_2 = QtWidgets.QLabel(self.groupBox_VBDD_byScript_2)
        self.label_VBDD_Script_2.setObjectName("label_VBDD_Script_2")
        self.horizontalLayout_6.addWidget(self.label_VBDD_Script_2)
        self.pushButton_VBDD_Script_2 = QtWidgets.QPushButton(self.groupBox_VBDD_byScript_2)
        self.pushButton_VBDD_Script_2.setIcon(icon1)
        self.pushButton_VBDD_Script_2.setObjectName("pushButton_VBDD_Script_2")
        self.horizontalLayout_6.addWidget(self.pushButton_VBDD_Script_2)
        self.verticalLayout_9.addWidget(self.groupBox_VBDD_byScript_2)
        self.tabWidget_VBDF.addTab(self.tabWidget_VBDF_Second_State, "")
        self.tabWidget_VBDF_Parameter = QtWidgets.QWidget()
        self.tabWidget_VBDF_Parameter.setObjectName("tabWidget_VBDF_Parameter")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tabWidget_VBDF_Parameter)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.groupBox_VBPD_byRead = QtWidgets.QGroupBox(self.tabWidget_VBDF_Parameter)
        self.groupBox_VBPD_byRead.setCheckable(True)
        self.groupBox_VBPD_byRead.setObjectName("groupBox_VBPD_byRead")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_VBPD_byRead)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_VBPD_CHid = QtWidgets.QLabel(self.groupBox_VBPD_byRead)
        self.label_VBPD_CHid.setObjectName("label_VBPD_CHid")
        self.horizontalLayout_14.addWidget(self.label_VBPD_CHid)
        self.label_VBPD_Force_id = QtWidgets.QLabel(self.groupBox_VBPD_byRead)
        self.label_VBPD_Force_id.setObjectName("label_VBPD_Force_id")
        self.horizontalLayout_14.addWidget(self.label_VBPD_Force_id)
        self.comboBox_VBPD_CHid = QtWidgets.QComboBox(self.groupBox_VBPD_byRead)
        self.comboBox_VBPD_CHid.setObjectName("comboBox_VBPD_CHid")
        self.horizontalLayout_14.addWidget(self.comboBox_VBPD_CHid)
        self.verticalLayout_17.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_VBPD_action = QtWidgets.QLabel(self.groupBox_VBPD_byRead)
        self.label_VBPD_action.setObjectName("label_VBPD_action")
        self.horizontalLayout_15.addWidget(self.label_VBPD_action)
        self.comboBox_VBPD_action = QtWidgets.QComboBox(self.groupBox_VBPD_byRead)
        self.comboBox_VBPD_action.setObjectName("comboBox_VBPD_action")
        self.horizontalLayout_15.addWidget(self.comboBox_VBPD_action)
        self.pushButton_VBPD_Populate = QtWidgets.QPushButton(self.groupBox_VBPD_byRead)
        self.pushButton_VBPD_Populate.setObjectName("pushButton_VBPD_Populate")
        self.horizontalLayout_15.addWidget(self.pushButton_VBPD_Populate)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_VBPD_Add = QtWidgets.QLabel(self.groupBox_VBPD_byRead)
        self.label_VBPD_Add.setObjectName("label_VBPD_Add")
        self.horizontalLayout_16.addWidget(self.label_VBPD_Add)
        self.lineEdit_VBPD_Add_Param = QtWidgets.QLineEdit(self.groupBox_VBPD_byRead)
        self.lineEdit_VBPD_Add_Param.setObjectName("lineEdit_VBPD_Add_Param")
        self.horizontalLayout_16.addWidget(self.lineEdit_VBPD_Add_Param)
        self.comboBox_VBPD_Add_Param_DB = QtWidgets.QComboBox(self.groupBox_VBPD_byRead)
        self.comboBox_VBPD_Add_Param_DB.setObjectName("comboBox_VBPD_Add_Param_DB")
        self.horizontalLayout_16.addWidget(self.comboBox_VBPD_Add_Param_DB)
        self.comboBox_VBPD_Add_Param_Op = QtWidgets.QComboBox(self.groupBox_VBPD_byRead)
        self.comboBox_VBPD_Add_Param_Op.setObjectName("comboBox_VBPD_Add_Param_Op")
        self.horizontalLayout_16.addWidget(self.comboBox_VBPD_Add_Param_Op)
        self.pushButton_VBPD_Add_Param = QtWidgets.QPushButton(self.groupBox_VBPD_byRead)
        self.pushButton_VBPD_Add_Param.setObjectName("pushButton_VBPD_Add_Param")
        self.horizontalLayout_16.addWidget(self.pushButton_VBPD_Add_Param)
        self.verticalLayout_17.addLayout(self.horizontalLayout_16)
        self.groupBox_VBPD_Parameters = QtWidgets.QGroupBox(self.groupBox_VBPD_byRead)
        self.groupBox_VBPD_Parameters.setCheckable(True)
        self.groupBox_VBPD_Parameters.setObjectName("groupBox_VBPD_Parameters")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_VBPD_Parameters)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.pushButton_VBPD_check_all = QtWidgets.QPushButton(self.groupBox_VBPD_Parameters)
        self.pushButton_VBPD_check_all.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/User-Interface-Checked-Checkbox-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBPD_check_all.setIcon(icon2)
        self.pushButton_VBPD_check_all.setObjectName("pushButton_VBPD_check_all")
        self.horizontalLayout_18.addWidget(self.pushButton_VBPD_check_all)
        self.pushButton_VBPD_uncheck_all = QtWidgets.QPushButton(self.groupBox_VBPD_Parameters)
        self.pushButton_VBPD_uncheck_all.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/User-Interface-Unchecked-Checkbox-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBPD_uncheck_all.setIcon(icon3)
        self.pushButton_VBPD_uncheck_all.setObjectName("pushButton_VBPD_uncheck_all")
        self.horizontalLayout_18.addWidget(self.pushButton_VBPD_uncheck_all)
        self.verticalLayout_14.addLayout(self.horizontalLayout_18)
        self.tableWidget_VBPD_parameters = QtWidgets.QTableWidget(self.groupBox_VBPD_Parameters)
        self.tableWidget_VBPD_parameters.setObjectName("tableWidget_VBPD_parameters")
        self.tableWidget_VBPD_parameters.setColumnCount(0)
        self.tableWidget_VBPD_parameters.setRowCount(0)
        self.verticalLayout_14.addWidget(self.tableWidget_VBPD_parameters)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.pushButton_VBPD_clear = QtWidgets.QPushButton(self.groupBox_VBPD_Parameters)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/bin-red-full-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBPD_clear.setIcon(icon4)
        self.pushButton_VBPD_clear.setObjectName("pushButton_VBPD_clear")
        self.horizontalLayout_17.addWidget(self.pushButton_VBPD_clear)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.pushButton_VBPD_clear_unchecked = QtWidgets.QPushButton(self.groupBox_VBPD_Parameters)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/trash-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBPD_clear_unchecked.setIcon(icon5)
        self.pushButton_VBPD_clear_unchecked.setObjectName("pushButton_VBPD_clear_unchecked")
        self.horizontalLayout_17.addWidget(self.pushButton_VBPD_clear_unchecked)
        self.pushButton_VBPD_clear_selected = QtWidgets.QPushButton(self.groupBox_VBPD_Parameters)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/Clear-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_VBPD_clear_selected.setIcon(icon6)
        self.pushButton_VBPD_clear_selected.setObjectName("pushButton_VBPD_clear_selected")
        self.horizontalLayout_17.addWidget(self.pushButton_VBPD_clear_selected)
        self.verticalLayout_14.addLayout(self.horizontalLayout_17)
        self.verticalLayout_17.addWidget(self.groupBox_VBPD_Parameters)
        self.verticalLayout_16.addWidget(self.groupBox_VBPD_byRead)
        self.tabWidget_VBDF.addTab(self.tabWidget_VBDF_Parameter, "")
        self.tabWidget_VBDF_Linking = QtWidgets.QWidget()
        self.tabWidget_VBDF_Linking.setObjectName("tabWidget_VBDF_Linking")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tabWidget_VBDF_Linking)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox_VBDD_Linkfrom = QtWidgets.QGroupBox(self.tabWidget_VBDF_Linking)
        self.groupBox_VBDD_Linkfrom.setObjectName("groupBox_VBDD_Linkfrom")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_Linkfrom)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.listWidget_VBDD_Linkfrom = QtWidgets.QListWidget(self.groupBox_VBDD_Linkfrom)
        self.listWidget_VBDD_Linkfrom.setObjectName("listWidget_VBDD_Linkfrom")
        self.verticalLayout_13.addWidget(self.listWidget_VBDD_Linkfrom)
        self.horizontalLayout_12.addWidget(self.groupBox_VBDD_Linkfrom)
        self.groupBox_VBDD_Linkto = QtWidgets.QGroupBox(self.tabWidget_VBDF_Linking)
        self.groupBox_VBDD_Linkto.setObjectName("groupBox_VBDD_Linkto")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_VBDD_Linkto)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.listWidget_VBDD_Linkto = QtWidgets.QListWidget(self.groupBox_VBDD_Linkto)
        self.listWidget_VBDD_Linkto.setObjectName("listWidget_VBDD_Linkto")
        self.verticalLayout_12.addWidget(self.listWidget_VBDD_Linkto)
        self.checkBox_VBPD_Show_Lines = QtWidgets.QCheckBox(self.groupBox_VBDD_Linkto)
        self.checkBox_VBPD_Show_Lines.setObjectName("checkBox_VBPD_Show_Lines")
        self.verticalLayout_12.addWidget(self.checkBox_VBPD_Show_Lines)
        self.horizontalLayout_12.addWidget(self.groupBox_VBDD_Linkto)
        self.tabWidget_VBDF.addTab(self.tabWidget_VBDF_Linking, "")
        self.tabWidget_VBDF_Transform = QtWidgets.QWidget()
        self.tabWidget_VBDF_Transform.setObjectName("tabWidget_VBDF_Transform")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabWidget_VBDF_Transform)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBoxgroupBox_VBDD_Transform = QtWidgets.QGroupBox(self.tabWidget_VBDF_Transform)
        self.groupBoxgroupBox_VBDD_Transform.setObjectName("groupBoxgroupBox_VBDD_Transform")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBoxgroupBox_VBDD_Transform)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_VBDD_Transform2 = QtWidgets.QGroupBox(self.groupBoxgroupBox_VBDD_Transform)
        self.groupBox_VBDD_Transform2.setObjectName("groupBox_VBDD_Transform2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_VBDD_Transform2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dial = QtWidgets.QDial(self.groupBox_VBDD_Transform2)
        self.dial.setObjectName("dial")
        self.gridLayout_5.addWidget(self.dial, 0, 0, 1, 1)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.groupBox_VBDD_Transform2)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout_5.addWidget(self.horizontalScrollBar, 2, 0, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_VBDD_Transform2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_5.addWidget(self.horizontalSlider, 1, 0, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(self.groupBox_VBDD_Transform2)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout_5.addWidget(self.verticalSlider, 0, 1, 1, 1)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.groupBox_VBDD_Transform2)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout_5.addWidget(self.verticalScrollBar, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_VBDD_Transform2)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 3, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_VBDD_Transform2)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lineEdit_VBTD_Transform = QtWidgets.QLineEdit(self.groupBoxgroupBox_VBDD_Transform)
        self.lineEdit_VBTD_Transform.setObjectName("lineEdit_VBTD_Transform")
        self.horizontalLayout_22.addWidget(self.lineEdit_VBTD_Transform)
        self.comboBoxVBTD_MacroFunctions = QtWidgets.QComboBox(self.groupBoxgroupBox_VBDD_Transform)
        self.comboBoxVBTD_MacroFunctions.setObjectName("comboBoxVBTD_MacroFunctions")
        self.horizontalLayout_22.addWidget(self.comboBoxVBTD_MacroFunctions)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        self.checkBox = QtWidgets.QCheckBox(self.groupBoxgroupBox_VBDD_Transform)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_11.addWidget(self.checkBox)
        self.tableView = QtWidgets.QTableView(self.groupBoxgroupBox_VBDD_Transform)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_11.addWidget(self.tableView)
        self.verticalLayout_10.addWidget(self.groupBoxgroupBox_VBDD_Transform)
        self.tabWidget_VBDF.addTab(self.tabWidget_VBDF_Transform, "")
        self.tabWidget_VBDF_Visualize = QtWidgets.QWidget()
        self.tabWidget_VBDF_Visualize.setObjectName("tabWidget_VBDF_Visualize")
        self.tabWidget_VBDF.addTab(self.tabWidget_VBDF_Visualize, "")
        self.verticalLayout.addWidget(self.tabWidget_VBDF)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_VBDD)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_VBDD)
        self.tabWidget_VBDF.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog_VBDD.accept)
        self.buttonBox.rejected.connect(Dialog_VBDD.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_VBDD)

    def retranslateUi(self, Dialog_VBDD):
        _translate = QtCore.QCoreApplication.translate
        Dialog_VBDD.setWindowTitle(_translate("Dialog_VBDD", "Variable Button Data Dialog"))
        self.groupBox_VBDD_General.setTitle(_translate("Dialog_VBDD", "GroupBox"))
        self.label_VBDD_Name.setText(_translate("Dialog_VBDD", "Name:"))
        self.label_VBDD_kind.setText(_translate("Dialog_VBDD", "Batton Kind:"))
        self.groupBox_VBDD_Position_Size.setTitle(_translate("Dialog_VBDD", "Position And Size"))
        self.label_VBDD_Position.setText(_translate("Dialog_VBDD", "Position"))
        self.label_VBDD_Size.setText(_translate("Dialog_VBDD", "Size"))
        self.label_VBDD_MarginSize.setText(_translate("Dialog_VBDD", "MarginSize"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tabWidget_VBDF_General), _translate("Dialog_VBDD", "General"))
        self.label_VBDD_id.setText(_translate("Dialog_VBDD", "Id:"))
        self.pushButton_VBDD_Icon.setText(_translate("Dialog_VBDD", "Select Icon"))
        self.label_VBDD_batton_type.setText(_translate("Dialog_VBDD", "Batton Type:"))
        self.groupBox_VBDD_byaction.setTitle(_translate("Dialog_VBDD", "By action"))
        self.label_VBDD_CHid.setText(_translate("Dialog_VBDD", "Force Id"))
        self.label_VBDD_Force_id.setText(_translate("Dialog_VBDD", "Force interface to:"))
        self.label_VBDD_action.setText(_translate("Dialog_VBDD", "Action"))
        self.groupBox_VBDD_Parameters.setTitle(_translate("Dialog_VBDD", "Show Parameters"))
        self.label_VBDD_Format.setText(_translate("Dialog_VBDD", "Action Format"))
        self.label_VBDD_Result.setText(_translate("Dialog_VBDD", "Action Result"))
        self.groupBox_VBDD_byGcode.setToolTip(_translate("Dialog_VBDD", "To send Gcode no action has to be selected."))
        self.groupBox_VBDD_byGcode.setTitle(_translate("Dialog_VBDD", "By Gcode"))
        self.groupBox_VBDD_byScript.setToolTip(_translate("Dialog_VBDD", "To send script no action and no Gcode must be present."))
        self.groupBox_VBDD_byScript.setTitle(_translate("Dialog_VBDD", "By Script"))
        self.label_VBDD_Script.setText(_translate("Dialog_VBDD", "No Script Selected"))
        self.pushButton_VBDD_Script.setText(_translate("Dialog_VBDD", "PushButton"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tabWidget_VBDF_First_State), _translate("Dialog_VBDD", "First State"))
        self.label_VBDD_id_2.setText(_translate("Dialog_VBDD", "Id:"))
        self.pushButton_VBDD_Icon_2.setText(_translate("Dialog_VBDD", "Select Icon"))
        self.label_VBDD_batton_type_2.setText(_translate("Dialog_VBDD", "Batton Type:"))
        self.groupBox_VBDD_byaction_2.setTitle(_translate("Dialog_VBDD", "By action"))
        self.label_VBDD_CHid_2.setText(_translate("Dialog_VBDD", "Force Id"))
        self.label_VBDD_Force_id_2.setText(_translate("Dialog_VBDD", "Force interface to:"))
        self.label_VBDD_action_2.setText(_translate("Dialog_VBDD", "Action"))
        self.groupBox_VBDD_Parameters_2.setTitle(_translate("Dialog_VBDD", "Show Parameters"))
        self.label_VBDD_Format_2.setText(_translate("Dialog_VBDD", "Action Format"))
        self.label_VBDD_Result_2.setText(_translate("Dialog_VBDD", "Action Result"))
        self.groupBox_VBDD_byGcode_2.setToolTip(_translate("Dialog_VBDD", "To send Gcode no action has to be selected."))
        self.groupBox_VBDD_byGcode_2.setTitle(_translate("Dialog_VBDD", "By Gcode"))
        self.groupBox_VBDD_byScript_2.setToolTip(_translate("Dialog_VBDD", "To send script no action and no Gcode must be present."))
        self.groupBox_VBDD_byScript_2.setTitle(_translate("Dialog_VBDD", "By Script"))
        self.label_VBDD_Script_2.setText(_translate("Dialog_VBDD", "No Script Selected"))
        self.pushButton_VBDD_Script_2.setText(_translate("Dialog_VBDD", "PushButton"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tabWidget_VBDF_Second_State), _translate("Dialog_VBDD", "Second State"))
        self.groupBox_VBPD_byRead.setTitle(_translate("Dialog_VBDD", "By Read action"))
        self.label_VBPD_CHid.setText(_translate("Dialog_VBDD", "Force Id"))
        self.label_VBPD_Force_id.setText(_translate("Dialog_VBDD", "Force interface to:"))
        self.label_VBPD_action.setText(_translate("Dialog_VBDD", "Action"))
        self.pushButton_VBPD_Populate.setText(_translate("Dialog_VBDD", "Populate"))
        self.label_VBPD_Add.setText(_translate("Dialog_VBDD", "Add:"))
        self.pushButton_VBPD_Add_Param.setText(_translate("Dialog_VBDD", "Add"))
        self.groupBox_VBPD_Parameters.setTitle(_translate("Dialog_VBDD", "Show Parameters"))
        self.pushButton_VBPD_clear.setText(_translate("Dialog_VBDD", "Clear All"))
        self.pushButton_VBPD_clear_unchecked.setText(_translate("Dialog_VBDD", "Clear Unchecked"))
        self.pushButton_VBPD_clear_selected.setText(_translate("Dialog_VBDD", "Clear Selected"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tabWidget_VBDF_Parameter), _translate("Dialog_VBDD", "Parameter"))
        self.groupBox_VBDD_Linkfrom.setTitle(_translate("Dialog_VBDD", "Link From"))
        self.groupBox_VBDD_Linkto.setTitle(_translate("Dialog_VBDD", "Link To"))
        self.checkBox_VBPD_Show_Lines.setText(_translate("Dialog_VBDD", "Show Connecting Lines"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tabWidget_VBDF_Linking), _translate("Dialog_VBDD", "Linking"))
        self.groupBoxgroupBox_VBDD_Transform.setTitle(_translate("Dialog_VBDD", "GroupBox"))
        self.groupBox_VBDD_Transform2.setTitle(_translate("Dialog_VBDD", "GroupBox"))
        self.label.setText(_translate("Dialog_VBDD", "TextLabel"))
        self.checkBox.setText(_translate("Dialog_VBDD", "CheckBox"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tabWidget_VBDF_Transform), _translate("Dialog_VBDD", "Transform"))
        self.tabWidget_VBDF.setTabText(self.tabWidget_VBDF.indexOf(self.tabWidget_VBDF_Visualize), _translate("Dialog_VBDD", "Visualize"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_VBDD = QtWidgets.QDialog()
    ui = Ui_Dialog_VBDD()
    ui.setupUi(Dialog_VBDD)
    Dialog_VBDD.show()
    sys.exit(app.exec_())
